
# Example project file that defines project level information

projectName: axi4sDemo

# project files can be regular input files, regular input files with additional projectFiles sections, or additional ProjectFiles.
# note in the case of additional project files any top level controls (such as schema:) are ignored
# relative path names are resolved based on location of project file (this includes sub projects)
projectFiles:
  - axi4sDemo_tb.yaml

# uncomment to use a custom schema file, otherwise the default schema is used
#dbSchema: config/schema.yaml

addressControl: config/addressControl.yaml

# This key indicates the top level block of the design
topInstance: axi4sDemo_tb

# uncomment to use custom templates, otherwise the default templates are used
#docConfig : config/docConfig.yaml
#cppConfig : config/cppConfig.yaml
#svConfig : config/svConfig.yaml

# this is a list of locations, orthogonal to design hierarchy, that maps out the functional layout of the project
# $xxx is a macro that is replaced by the directory. Note macro replacement only works as first character
# root defines the top level directory for the project, and other directories are defined relative to this.
# note that $a2c is automatically created by the system and points to the a2c directory
dirs:
  root: ../..    # project root directory relative to project file - required
  base: $root/base             # for block base classes
  model: $root/model           # systemC model implementation
  rtl: $root/rtl               # RTL implementation
  vl_wrap: $root/verif/vl_wrap # rtl wrapper files
  tb: $root/tb                 # testbench definition files
  fwInc: $root/fw/include      # firmware include files

# information about project directory structure to enable simplified maintenance
# and generation of file for new blocks. Note that directory structure will mirror
# architecture hierarchy.
fileGeneration:
  template: $a2c/templates/fileGen/fileGen.py
  fileMap:
    # generation has 2 modes, block and context
    # block creates a file per design block and cond: depend on the block definition
    # context creates a file per yaml file and cond: depend on the yaml file (typically this is for includes/packages)
    # name will be added to the module name to generate a filename plus associated extensions
    # path to the file is based on dirs section and otherwise follows block/yaml file structure
    # this means if blocks are defined in a file called cpu/cpu.yaml ie in the cpu directory then the implementation file is in cpu unless overridden in the block definition
    # if blockDirs is true then the file is placed in a directory the block appended as well
    # note that basePath should reference a path key in the dirs section
    # cond: matches fields in the block definition, if all fields are true then the file is generated
    # smartInclude is yaml based instead of block based and is used to generate include files based on the yaml file
    # if smartInclude is true then files are only created if there is content to include. If smartInclude: false then the file is always created
    blockBase   : { name : "Base",            ext: {hdr: "h"},             cond: {hasMdl: true, hasTb: true},   mode: block,   basePath: base,    desc: "Module Base class header file"}
    block       : { name : "",                ext: {hdr: "h", src: "cpp"}, cond: {hasMdl: true},                mode: block,   basePath: model,   desc: "Model implementation file"}
    rtlModule   : { name : "",                ext: {sv: "sv"},             cond: {hasRtl: true},                mode: block,   basePath: rtl,     desc: "RTL implementation file"}
    vlSvWrap    : { name : "_hdl_sv_wrapper", ext: {sv: "sv"},             cond: {hasVl: true},                 mode: block,   basePath: vl_wrap, variant: true, desc: "SystemVerilog HDL module wrapper for verilator"}
    vlScWrap    : { name : "_hdl_sc_wrapper", ext: {hdr: "h"},             cond: {hasVl: true},                 mode: block,   basePath: vl_wrap, desc: "SystemC Verilated HDL module derived class header file"}
    # tandem      : { name : "Tandem",          ext: {hdr: "h", src: "cpp"}, cond: {hasMdl: true, hasRtl: true},  mode: block,   basePath: base,    desc: "Model tandem module wrapper class header file"}
    testBench   : { name : "Testbench",       ext: {hdr: "h", src: "cpp"}, cond: {hasTb: true}, blockDir: true, mode: block,   basePath: tb,      desc: "Testbench implementation file"}
    tbConfig    : { name : "Config",          ext: {src: "cpp"},           cond: {hasTb: true}, blockDir: true, mode: block,   basePath: tb,      desc: "Testbench config files"}
    tbExternal  : { name : "External",        ext: {hdr: "h", src: "cpp"}, cond: {hasTb: true}, blockDir: true, mode: block,   basePath: tb,      desc: "Testbench external files"}
    include     : { name : "Includes",        ext: {hdr: "h", src: "cpp"}, cond: {smartInclude: true},          mode: context, basePath: model,   desc: "yaml based include file"}
    includeFW   : { name : "IncludesFW",      ext: {hdr: "h", src: "cpp"}, cond: {smartInclude: true},          mode: context, basePath: fwInc,   desc: "yaml based fw include file"}
    package     : { name : "_package",        ext: {sv: "sv"},             cond: {smartInclude: true},          mode: context, basePath: rtl,     desc: "yaml based package file"}
  # standard copyright statement to be added to all generated files - change to suite your company
  fileCopyrightStatement: ""
postProcess:
  - $a2c/config/postParseRegister.py
  - $a2c/config/postParseChecks.py
