
all:
	$(MAKE) -C model all
	$(MAKE) -C systemVerilog all
	$(MAKE) -C verif all

run:
	$(MAKE) -C model 
	$(MAKE) -C verif 

clean:
	$(MAKE) -C model clean
	$(MAKE) -C systemVerilog clean
	$(MAKE) -C verif clean
