// copyright the arch2code project contributors, see https://bitbucket.org/arch2code/arch2code/src/main/LICENSE
#ifndef AXI_READ_CHANNEL_H
#define AXI_READ_CHANNEL_H

#include "sysc/kernel/sc_dynamic_processes.h"
#include "sysc/communication/sc_communication_ids.h"
#include "sysc/communication/sc_prim_channel.h"
#include "rdy_vld_channel.h"
#include "sysc/kernel/sc_event.h"
#include "sysc/kernel/sc_simcontext.h"
#include "sysc/tracing/sc_trace.h"
#include <typeinfo>
#include <iostream>
#include "portBase.h"
#include "interfaceBase.h"
#include "pingPongBuffer.h"
#include "bitTwiddling.h"
#include <memory>
#include <vector>
#include "simpleQueue.h"
#include <format>
#include "axiCommon.h"
#include "optionalPayload.h"

// sendAddr( A )
//          -------> receiveAddr( &A )
//          <------- sendData( D )
// receiveData( &D )

// id_t is optional, so its payload type ID and its bit width IDW sit last in
// the template argument list, after the USER sidebands (ARU, RU): ID defaults
// to _axiIdT and IDW to 4, the width the companion SV interface and C++
// templates already default an unbound id_t to.
template <typename D, typename U = std::monostate, typename ID = _axiIdT, unsigned IDW = 4>
struct axiReadRespSt
{
    ID rid; // Slave Read ID tag. This signal is the identification tag for the read data group of signals generated by the slave
    D rdata;     // Slave Read data
    _axiResponseT rresp; // Slave Read response. This signal indicates the status of the read transfer
    bool rlast; // Slave Read last. This signal indicates the last transfer in a read burst transaction
    // RUSER sideband, qualified by the read data channel handshake. Declared
    // last so that an empty U occupies tail padding and leaves the offsets of
    // every other member untouched.
    [[no_unique_address]] U user;

    static constexpr unsigned int idWidth = IDW; // number of bits in rid
    static constexpr unsigned int respWidth = 2; // number of bits in rresp
    static constexpr unsigned int dataWidth = D::_bitWidth; // number of bits in data
    static constexpr unsigned int lastWidth = 1; // number of bits in rlast
    static constexpr unsigned int userWidth = optionalPayloadBitWidth<U>(); // number of bits in user

    static constexpr unsigned int _bitWidth = idWidth + dataWidth + respWidth + lastWidth + userWidth;
    static constexpr unsigned int _byteWidth = (_bitWidth + 7)>>3;
    static constexpr unsigned int _packedSize = (_byteWidth + 7)>>3;

    typedef uint64_t _packedSt[_packedSize];

    axiReadRespSt() {};

    static int getBurstSize(void) { return(sizeof(D));} // returns datapath width in bytes

    inline D * getDataPtr(void) {return &rdata;} // returns pointer to internal data element. Note this is unrelated to any backdoor

    inline bool operator == (const axiReadRespSt< D, U, ID, IDW > & rhs) const {
        if constexpr (hasOptionalPayload<U>) {
            if (!(rhs.user == user)) { return false; }
        }
        return (
            rhs.rid == rid &&
            rhs.rdata == rdata &&
            rhs.rresp == rresp &&
            rhs.rlast == rlast
        );
    }
    inline friend void sc_trace(sc_trace_file *tf, const axiReadRespSt< D, U, ID, IDW > & v, const std::string & NAME ) {
        sc_trace(tf,v.rid, NAME + ".rid");
        sc_trace(tf,v.rdata, NAME + ".rdata");
        sc_trace(tf,v.rresp, NAME + ".rresp");
        sc_trace(tf,v.rlast, NAME + ".rlast");
        if constexpr (hasOptionalPayload<U>) { sc_trace(tf,v.user, NAME + ".ruser"); }
    }
    inline friend ostream& operator << ( ostream& os,  axiReadRespSt< D, U, ID, IDW > const & v ) {
        os << "("
           << std::hex << std::setw(1) << (int)v.rid << ", "
           << v.rdata.prt() << ", "
           << _axiResponseT_prt(v.rresp) << ", "
           << std::hex << std::setw(1) << (int)v.rlast << ");";
        return os;
    }
    std::string prt(bool all=false) const
    {
        std::stringstream ss;
        ss << "rid:0x" << std::hex << std::setw(1) << (int)rid
           << " rdata:" << rdata.prt()
           << " rresp:" << _axiResponseT_prt(rresp)
           << " rlast:0x" << std::hex << std::setw(1) << (int)rlast;
        return(ss.str());
    }
    static const char * getValueType(void)
    {
        return( D::getValueType() );
    }
    inline uint64_t getStructValue(void) const
    {
        return( rdata.getStructValue() );
    }
    inline void pack(_packedSt &_ret) const
    {
        uint16_t _pos{0};
        memset(&_ret, 0, axiReadRespSt::_byteWidth);
        pack_bits((uint64_t *)&_ret, _pos, rid, idWidth);
        _pos += idWidth;
        {
            typename D::_packedSt _tmp{0};
            rdata.pack(_tmp);
            pack_bits((uint64_t *)&_ret, _pos, (uint64_t *)&_tmp, dataWidth);
        }
        _pos += dataWidth;
        pack_bits((uint64_t *)&_ret, _pos, rresp, respWidth);
        _pos += respWidth;
        pack_bits((uint64_t *)&_ret, _pos, rlast, lastWidth);
        _pos += lastWidth;
        if constexpr (hasOptionalPayload<U>) {
            typename U::_packedSt _tmp{0};
            user.pack(_tmp);
            pack_bits((uint64_t *)&_ret, _pos, (uint64_t *)&_tmp, userWidth);
            _pos += userWidth;
        }
    }
    inline void unpack(_packedSt &_src)
    {
        uint16_t _pos{0};
        rid = (ID)((_src[ _pos >> 6 ] >> (_pos & 63)) & ((1ULL << idWidth) - 1));
        _pos += idWidth;
        {
            typename D::_packedSt _tmp{0};
            pack_bits((uint64_t *)&_tmp, 0, (uint64_t *)&_src, _pos, dataWidth);
            rdata.unpack(_tmp);
        }
        _pos += dataWidth;
        rresp = (_axiResponseT)((_src[ _pos >> 6 ] >> (_pos & 63)) & ((1ULL << respWidth) - 1));
        _pos += respWidth;
        rlast = (bool)((_src[ _pos >> 6 ] >> (_pos & 63)) & ((1ULL << lastWidth) - 1));
        _pos += lastWidth;
        if constexpr (hasOptionalPayload<U>) {
            typename U::_packedSt _tmp{0};
            pack_bits((uint64_t *)&_tmp, 0, (uint64_t *)&_src, _pos, userWidth);
            user.unpack(_tmp);
            _pos += userWidth;
        }
    }

};

template <typename A, typename U = std::monostate, typename ID = _axiIdT, unsigned IDW = 4>
struct axiReadAddressSt
{
    ID          arid;    // Master Read address ID. This signal is the identification tag for the read address group of signals (4bits)
    A           araddr;  // Master Read address. The read address gives the address of the first transfer in a read burst transaction
    uint8_t     arlen;   // Master Burst length. This signal indicates the exact number of transfers in a burst.
    _axiSizeT   arsize;  // Master Burst size. This signal indicates the size of each transfer in the burst.
    _axiBurstT  arburst; // Master Burst type. The burst type and the size information determine how the address for each transfer within the burst is calculated
    // ARUSER sideband, qualified by the read address channel handshake.
    // Declared last so that an empty U occupies tail padding and leaves the
    // offsets of every other member untouched.
    [[no_unique_address]] U user;

    static constexpr unsigned int idWidth = IDW; // number of bits in arid
    static constexpr unsigned int addrWidth = A::_bitWidth; // number of bits in araddr
    static constexpr unsigned int lenWidth = 8; // number of bits in arlen
    static constexpr unsigned int sizeWidth = 3; // number of bits in arsize
    static constexpr unsigned int burstWidth = 2; // number of bits in arburst
    static constexpr unsigned int userWidth = optionalPayloadBitWidth<U>(); // number of bits in user

    static constexpr unsigned int _bitWidth = idWidth + addrWidth + lenWidth + sizeWidth + burstWidth + userWidth;
    static constexpr unsigned int _byteWidth = (_bitWidth + 7)>>3;
    static constexpr unsigned int _packedSize = (_byteWidth + 7)>>3;

    typedef uint64_t _packedSt[_packedSize];

    axiReadAddressSt() {};

    inline bool operator == (const axiReadAddressSt< A, U, ID, IDW > & rhs) const {
        if constexpr (hasOptionalPayload<U>) {
            if (!(rhs.user == user)) { return false; }
        }
        return (
            rhs.arid == arid &&
            rhs.araddr == araddr &&
            rhs.arlen == arlen &&
            rhs.arsize == arsize &&
            rhs.arburst == arburst
        );
    }
    inline friend void sc_trace(sc_trace_file *tf, const axiReadAddressSt< A, U, ID, IDW > & v, const std::string & NAME ) {
        sc_trace(tf,v.arid, NAME + ".arid");
        sc_trace(tf,v.araddr, NAME + ".araddr");
        sc_trace(tf,v.arlen, NAME + ".arlen");
        sc_trace(tf,v.arsize, NAME + ".arsize");
        sc_trace(tf,v.arburst, NAME + ".arburst");
        if constexpr (hasOptionalPayload<U>) { sc_trace(tf,v.user, NAME + ".aruser"); }
    }
    inline friend ostream& operator << ( ostream& os, axiReadAddressSt< A, U, ID, IDW > const & v ) {
        os << "("
           << (int)v.arid << ", "
           << v.araddr.prt() << ", "
           << (int)v.arlen << ", "
           << (int)v.arsize << ", "
           << _axiBurstT_prt(v.arburst) << ");";
        return os;
    }
    std::string prt(bool all=false) const
    {
        std::stringstream ss;
        ss << "arid:0x" << std::hex << std::setw(1) << (int)arid
           << " araddr:" << araddr.prt()
           << " arlen:0x" << std::hex << std::setw(2) << std::setfill('0') << (int)arlen
           << " arsize:0x" << std::hex << std::setw(1) << (int)arsize
           << " arburst:" << _axiBurstT_prt(arburst);
        return(ss.str());
    }
    static const char * getValueType(void)
    {
        return( A::getValueType() );
    }
    inline uint64_t getStructValue(void) const
    {
        return( araddr.getStructValue() );
    }
    inline void pack(_packedSt &_ret) const
    {
        uint16_t _pos{0};
        memset(&_ret, 0, axiReadAddressSt::_byteWidth);
        pack_bits((uint64_t *)&_ret, _pos, arid, idWidth);
        _pos += idWidth;
        {
            typename A::_packedSt _tmp{0};
            araddr.pack(_tmp);
            pack_bits((uint64_t *)&_ret, _pos, (uint64_t *)&_tmp, addrWidth);
        }
        _pos += addrWidth;
        pack_bits((uint64_t *)&_ret, _pos, arlen, lenWidth);
        _pos += lenWidth;
        pack_bits((uint64_t *)&_ret, _pos, arsize, sizeWidth);
        _pos += sizeWidth;
        pack_bits((uint64_t *)&_ret, _pos, arburst, burstWidth);
        _pos += burstWidth;
        if constexpr (hasOptionalPayload<U>) {
            typename U::_packedSt _tmp{0};
            user.pack(_tmp);
            pack_bits((uint64_t *)&_ret, _pos, (uint64_t *)&_tmp, userWidth);
            _pos += userWidth;
        }
    }
    inline void unpack(_packedSt &_src)
    {
        uint16_t _pos{0};
        arid = (ID)((_src[ _pos >> 6 ] >> (_pos & 63)) & ((1ULL << idWidth) - 1));
        _pos += idWidth;
        {
            typename A::_packedSt _tmp{0};
            pack_bits((uint64_t *)&_tmp, 0, (uint64_t *)&_src, _pos, addrWidth);
            araddr.unpack(_tmp);
        }
        _pos += addrWidth;
        arlen = (uint8_t)((_src[ _pos >> 6 ] >> (_pos & 63)) & ((1ULL << lenWidth) - 1));
        _pos += lenWidth;
        arsize = (_axiSizeT)((_src[ _pos >> 6 ] >> (_pos & 63)) & ((1ULL << sizeWidth) - 1));
        _pos += sizeWidth;
        arburst = (_axiBurstT)((_src[ _pos >> 6 ] >> (_pos & 63)) & ((1ULL << burstWidth) - 1));
        _pos += burstWidth;
        if constexpr (hasOptionalPayload<U>) {
            typename U::_packedSt _tmp{0};
            pack_bits((uint64_t *)&_tmp, 0, (uint64_t *)&_src, _pos, userWidth);
            user.unpack(_tmp);
            _pos += userWidth;
        }
    }

};

template <class A, class D, class ARU = std::monostate, class RU = std::monostate, class ID = _axiIdT, unsigned IDW = 4>
class axi_read_in_if
: virtual public sc_interface, virtual public portBase
{
public:

    // blocking read
    virtual void receiveAddr( axiReadAddressSt<A, ARU, ID, IDW>& ) = 0;
    virtual void sendData( const axiReadRespSt<D, RU, ID, IDW>& ) = 0;
    virtual void sendData( const axiReadRespSt<D, RU, ID, IDW>&, int burst_count ) = 0;
    virtual void sendDataCycle( const axiReadRespSt<D, RU, ID, IDW>& ) = 0;
    virtual uint8_t * getWritePtr(void) = 0;

protected:
    // constructor
    axi_read_in_if()
        {}

private:
    // disabled
    axi_read_in_if( const axi_read_in_if<A, D, ARU, RU, ID, IDW>& );
    axi_read_in_if<A, D, ARU, RU, ID, IDW>& operator = ( const axi_read_in_if<A, D, ARU, RU, ID, IDW>& );
};


template <class A, class D, class ARU = std::monostate, class RU = std::monostate, class ID = _axiIdT, unsigned IDW = 4>
class axi_read_out_if
: virtual public sc_interface, virtual public portBase
{
public:
    // blocking write
    virtual void sendAddr( const axiReadAddressSt<A, ARU, ID, IDW>&, std::optional<std::string> str=std::nullopt ) = 0;
    virtual void receiveData( axiReadRespSt<D, RU, ID, IDW>& ) = 0;
    virtual void receiveDataCycle(  axiReadRespSt<D, RU, ID, IDW>& ) = 0;  // for multi cycle channels, gets one burst
    virtual uint8_t * getReadPtr(void) = 0;
    virtual void push_burst(uint32_t burstCount) = 0;

protected:
    // constructor
    axi_read_out_if()
        {}

private:
    // disabled
    axi_read_out_if( const axi_read_out_if<A, D, ARU, RU, ID, IDW>& );
    axi_read_out_if<A, D, ARU, RU, ID, IDW>& operator = ( const axi_read_out_if<A, D, ARU, RU, ID, IDW>& );
};

class axi_read_transaction_counter {
public:
    inline static uint64_t transactionNo{0};
};

template <class A, class D, class ARU = std::monostate, class RU = std::monostate, class ID = _axiIdT, unsigned IDW = 4>
class axi_read_channel
: public axi_read_in_if<A, D, ARU, RU, ID, IDW>,
  public axi_read_out_if<A, D, ARU, RU, ID, IDW>,
  public sc_prim_channel,
  public axi_read_transaction_counter
{
public:
    // Each AXI channel allocates several vectors of transactionIdMax entries,
    // so its footprint grows as 2^IDW; ID must be wide enough to hold IDW
    // bits, since the id is stored in it directly rather than packed.
    static_assert(IDW >= 1 && IDW <= 16 && IDW <= 8 * sizeof(ID), "IDW must be >= 1 and <= 16, otherwise the per-channel transaction-tracking vectors (sized 2^IDW) become impractically large, and must fit in ID");
    static constexpr unsigned int transactionIdMax = 1u << IDW;

    // constructor const char * module, std::string block
    explicit axi_read_channel( const char* name_, std::string block_, INTERFACE_AUTO_MODE autoMode=INTERFACE_AUTO_OFF)
      : sc_prim_channel( name_ ),
        m_addr_channel((std::string(name_) + "addr").c_str(), block_),
        m_data_channel((std::string(name_) + "data").c_str(), block_),
        m_addr_out((std::string(name_) + "addrOut").c_str()),
        m_data_out((std::string(name_) + "dataOut").c_str()),
        m_addr_in((std::string(name_) + "addrIn").c_str()),
        m_data_in((std::string(name_) + "dataIn").c_str()),
        m_reader(nullptr),
        m_writer(nullptr),
        m_transaction_pipeline(transactionIdMax, simpleQueue<_axi_transaction_st>(3)),
        m_transactions(transactionIdMax),
        m_active_read_transactions(transactionIdMax),
        m_active_write_transactions(transactionIdMax),
        m_read_cycle(transactionIdMax, 0),
        m_write_cycle(transactionIdMax, 0),
        m_logQueueAddr(std::make_shared<stringPingPong>()),
        m_logQueueData(std::make_shared<stringPingPong>())
        {
            m_addr_in( m_addr_channel );
            m_addr_out( m_addr_channel );
            m_data_in( m_data_channel );
            m_data_out( m_data_channel );
            m_data_channel.setLogQueue(m_logQueueData);
            m_addr_channel.setLogQueue(m_logQueueAddr);
        }

    explicit axi_read_channel( const char* name_, std::string block_, std::string multiCycleType_, int pingpong_size_, std::string trackerName_, INTERFACE_AUTO_MODE autoMode=INTERFACE_AUTO_OFF)
      : sc_prim_channel( name_ ),
        m_addr_channel((std::string(name_) + "addr").c_str(), block_),
        m_data_channel((std::string(name_) + "data").c_str(), block_, multiCycleType_, pingpong_size_ * sizeof(axiReadRespSt<D, RU, ID, IDW>), trackerName_),
        m_addr_out((std::string(name_) + "addrOut").c_str()),
        m_data_out((std::string(name_) + "dataOut").c_str()),
        m_addr_in((std::string(name_) + "addrIn").c_str()),
        m_data_in((std::string(name_) + "dataIn").c_str()),
        m_reader(nullptr),
        m_writer(nullptr),
        m_transaction_pipeline(transactionIdMax, simpleQueue<_axi_transaction_st>(3)),
        m_transactions(transactionIdMax),
        m_active_read_transactions(transactionIdMax),
        m_active_write_transactions(transactionIdMax),
        m_read_cycle(transactionIdMax, 0),
        m_write_cycle(transactionIdMax, 0),
        m_logQueueAddr(std::make_shared<stringPingPong>()),
        m_logQueueData(std::make_shared<stringPingPong>())
        {
            m_addr_in( m_addr_channel );
            m_addr_out( m_addr_channel );
            m_data_in( m_data_channel );
            m_data_out( m_data_channel );
            Q_ASSERT(multiCycleType_ =="" || multiCycleType_ == "api_list_size" || multiCycleType_ == "fixed_size", "multiCycleType must be api_list_size or fixed_size");
            m_data_channel.setLogQueue(m_logQueueData);
            m_addr_channel.setLogQueue(m_logQueueAddr);
        }

    // destructor
    virtual ~axi_read_channel() { }

    // interface methods
    virtual void register_port( sc_port_base&, const char* ) override;

    // out interfaces
    virtual void sendAddr( const axiReadAddressSt<A, ARU, ID, IDW>&, std::optional<std::string> str ) override;
    virtual void receiveData( axiReadRespSt<D, RU, ID, IDW>& ) override;
    virtual void receiveDataCycle( axiReadRespSt<D, RU, ID, IDW>& ) override;
    virtual uint8_t * getReadPtr( void ) override;
    virtual void push_burst(uint32_t burstCount) override { m_data_in->push_context(burstCount * sizeof(axiReadRespSt<D, RU, ID, IDW>)); }

    // in interfaces
    virtual void receiveAddr( axiReadAddressSt<A, ARU, ID, IDW>& ) override;
    virtual void sendData( const axiReadRespSt<D, RU, ID, IDW>& ) override;
    virtual void sendData( const axiReadRespSt<D, RU, ID, IDW>&, int burst_count ) override;
    virtual void sendDataCycle( const axiReadRespSt<D, RU, ID, IDW>& ) override;
    virtual uint8_t * getWritePtr(void) override;

    // other methods
    void trace( sc_trace_file* tf ) const override;

    virtual void print( ::std::ostream& = ::std::cout ) const override;
    virtual void dump( ::std::ostream& = ::std::cout ) const override;
    virtual void status(void);

    virtual const char* kind() const override
        { return "axi_read_channel"; }

    // portBase overrides
    void setMultiDriver(std::string name_, std::function<std::string(const uint64_t &value)> prt = nullptr) override
    {
        Q_ASSERT(false, std::format("multiple drivers on {} axiRd interface is invalid", name_ ));
    }
    std::shared_ptr<trackerBase> getTracker(void) override { return (m_data_in->getTracker());}
    virtual void setTeeBusy(bool busy) override { m_data_in->setTeeBusy(busy); }
    virtual void setTandem(void) override { m_addr_channel.setTandem(); m_data_channel.setTandem(); }
    virtual void setLogging(verbosity_e verbosity) override { m_addr_channel.setLogging(verbosity); m_data_channel.setLogging(verbosity); }
    virtual void setTimed(int nsec, timedDelayMode mode) override { m_addr_channel.setTimed(nsec, mode); m_data_channel.setTimed(nsec, mode); }
    virtual void setCycleTransaction(portType type_) override
    {
        m_cycle_transaction = true;
        m_data_out->setCycleTransaction();
        m_data_in->setCycleTransaction();
    }
    virtual sc_prim_channel* getChannel(void) override { return this; }
protected:
    rdy_vld_channel<axiReadAddressSt<A, ARU, ID, IDW>> m_addr_channel;
    rdy_vld_channel<axiReadRespSt<D, RU, ID, IDW>> m_data_channel;
public: // make these public for the tees/verif
    rdy_vld_out <axiReadAddressSt<A, ARU, ID, IDW>> m_addr_out; // for sending address (axi_out)
    rdy_vld_out <axiReadRespSt<D, RU, ID, IDW>> m_data_out; // for sending data (axi_in)
    rdy_vld_in <axiReadAddressSt<A, ARU, ID, IDW>> m_addr_in; // for receiving address (axi_in)
    rdy_vld_in <axiReadRespSt<D, RU, ID, IDW>> m_data_in; // for receiving data (axi_out)

protected:
    sc_port_base* m_reader; // used for static design rule checking
    sc_port_base* m_writer; // used for static design rule checking

private:
    std::vector<simpleQueue<_axi_transaction_st>> m_transaction_pipeline; // queue of transactions from response side to read side
    std::vector<std::queue<_axi_transaction_st>> m_transactions; // queue of transactions by transaction id per axi
    std::vector<_axi_transaction_st> m_active_read_transactions;
    std::vector<_axi_transaction_st> m_active_write_transactions;
    bool m_cycle_transaction = false;
    std::vector<int> m_read_cycle;
    std::vector<int> m_write_cycle;
    // disabled
    axi_read_channel( const axi_read_channel<A, D, ARU, RU, ID, IDW>& );
    axi_read_channel& operator = ( const axi_read_channel<A, D, ARU, RU, ID, IDW>& );
    std::shared_ptr<stringPingPong> m_logQueueAddr;
    std::shared_ptr<stringPingPong> m_logQueueData;
    void manageSendDataTransaction(const axiReadRespSt<D, RU, ID, IDW> & data_);
    void manageReceiveDataTransaction(const axiReadRespSt<D, RU, ID, IDW> & data_);
    void handleSendTransactionLog(ID id);
};

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::register_port( sc_port_base& port_,
                const char* if_typename_ )
{
    std::string nm( if_typename_ );
    if( nm == typeid( axi_read_in_if<A, D, ARU, RU, ID, IDW> ).name() )
    {
        // only one reader can be connected
        if( m_reader != 0 ) {
            SC_REPORT_ERROR( SC_ID_MORE_THAN_ONE_FIFO_READER_, 0 );
            // may continue, if suppressed
        }
        m_reader = &port_;
    } else if( nm == typeid( axi_read_out_if<A, D, ARU, RU, ID, IDW> ).name() )
    {
        // only one writer can be connected
        if( m_writer != 0 ) {
            SC_REPORT_ERROR( SC_ID_MORE_THAN_ONE_FIFO_WRITER_, 0 );
            // may continue, if suppressed
        }
        m_writer = &port_;
    }
    else
    {
        SC_REPORT_ERROR( SC_ID_BIND_IF_TO_PORT_,
                         "axi_read_channel<A, D> port not recognized" );
        // may continue, if suppressed
    }
}

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::manageSendDataTransaction(const axiReadRespSt<D, RU, ID, IDW> & data_)
{
    if (m_transactions[data_.rid].empty()) {
        m_data_channel.log_.logPrint(std::format("transaction id not valid: {}", data_.prt()));
        Q_ASSERT(false, "transaction id not valid");
    }
    m_active_write_transactions[data_.rid] = m_transactions[data_.rid].front();
    m_transactions[data_.rid].pop();
    m_transaction_pipeline[data_.rid].emplace(m_active_write_transactions[data_.rid]);
}
template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::manageReceiveDataTransaction(const axiReadRespSt<D, RU, ID, IDW> & data_)
{
    if (m_transaction_pipeline[data_.rid].isEmpty()) {
        m_data_channel.log_.logPrint(std::format("transaction id not valid: {}", data_.prt()));
        Q_ASSERT(false, "transaction id not valid");
    }
    m_active_read_transactions[data_.rid] = m_transaction_pipeline[data_.rid].pop();
}

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::handleSendTransactionLog(ID id)
{
    if (m_data_channel.log_.isMatch(LOG_NORMAL)) {
        if (m_active_write_transactions[id].transactionStr) {
            m_logQueueData->push(*m_active_write_transactions[id].transactionStr);
        } else {
            m_logQueueData->push(std::format("RTX#{:x} ",m_active_write_transactions[id].transactionNo));
        }
    }
}
// blocking transactional read
template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::receiveAddr( axiReadAddressSt<A, ARU, ID, IDW> &addr_ )
{
    m_addr_in->read(addr_);
}

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::receiveData( axiReadRespSt<D, RU, ID, IDW> &data_ )
{
    Q_ASSERT(!m_cycle_transaction, "receiveData not valid api for cycle based transactions");
    m_data_in->read(data_);
    manageReceiveDataTransaction(data_);
}

// return getReadPtr based on current read buffer index
template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline uint8_t * axi_read_channel<A, D, ARU, RU, ID, IDW>::getReadPtr()
{
    Q_ASSERT(!m_cycle_transaction, "getReadPtr not valid api for cycle based transactions");
    return m_data_in->getReadPtr();
}

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline uint8_t * axi_read_channel<A, D, ARU, RU, ID, IDW>::getWritePtr()
{
    Q_ASSERT(!m_cycle_transaction, "getWritePtr not valid api for cycle based transactions");
    return m_data_out->getWritePtr();
}


template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
void axi_read_channel<A, D, ARU, RU, ID, IDW>::receiveDataCycle(  axiReadRespSt<D, RU, ID, IDW> & data_)
{
    Q_ASSERT(m_cycle_transaction, "receiveDataCycle not valid api for non cycle based transactions, make sure you setCycleTransaction(PORTTYPE_IN)");
    m_data_in->readClocked(data_);
    // if first cycle perform checks
    if (m_read_cycle[data_.rid] == 0) {
        manageReceiveDataTransaction(data_);
    }
    bool last = (m_read_cycle[data_.rid] == m_active_read_transactions[data_.rid].len);
    // manage last
    if (data_.rlast != last) {
        // error case is when responder is cycle based and last is not set correctly
        Q_ASSERT(false, "last set incorrectly");
    }

    m_read_cycle[data_.rid]++;
    if (last) {
        // on last cycle reset to zero to indicate the transaction is complete
        m_read_cycle[data_.rid] = 0;
    }
}

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::sendAddr( const axiReadAddressSt<A, ARU, ID, IDW>& addr_, std::optional<std::string> str)
{
    if (m_addr_channel.log_.isMatch(LOG_NORMAL)) {
        if (str) {
            m_logQueueAddr->push(*str);
        } else {
            m_logQueueAddr->push(std::format("RTX#{:x} ",transactionNo));
        }
    }
    m_transactions[addr_.arid].emplace(addr_.arid, addr_.arlen, addr_.arsize, transactionNo++, std::move(str));
    m_addr_out->write(addr_);
}

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
void axi_read_channel<A, D, ARU, RU, ID, IDW>::sendData( const axiReadRespSt<D, RU, ID, IDW>& data_ )
{
    Q_ASSERT(!m_cycle_transaction, "receiveData not valid api for cycle based transactions");
    manageSendDataTransaction(data_);
    handleSendTransactionLog(data_.rid);
    m_data_out->write(data_);
}
template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
void axi_read_channel<A, D, ARU, RU, ID, IDW>::sendData( const axiReadRespSt<D, RU, ID, IDW>& data_, int burst_count )
{
    Q_ASSERT(!m_cycle_transaction, "receiveData not valid api for cycle based transactions");
    manageSendDataTransaction(data_);
    handleSendTransactionLog(data_.rid);
    m_data_out->write(data_, burst_count * sizeof(axiReadRespSt<D, RU, ID, IDW>));
}


template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::sendDataCycle( const axiReadRespSt<D, RU, ID, IDW>& data_)
{
    Q_ASSERT(m_cycle_transaction, "receiveDataCycle not valid api for non cycle based transactions, make sure you setCycleTransaction(PORTTYPE_IN)");
    if (m_write_cycle[data_.rid] == 0) {
        manageSendDataTransaction(data_);
    }
    bool last = (m_write_cycle[data_.rid] == m_active_write_transactions[data_.rid].len);

    m_write_cycle[data_.rid]++;
    if (last) {
        // on last cycle reset to zero to indicate the transaction is complete
        m_write_cycle[data_.rid] = 0;
    }

    handleSendTransactionLog(data_.rid);
    m_data_out->writeClocked(data_);
}


template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
void axi_read_channel<A, D, ARU, RU, ID, IDW>::status(void)
{
    // nothing useful yet, as internal interfaces will give their own status
    //teeStatus();
}

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::trace( sc_trace_file* tf ) const
{
    (void) tf; /* ignore potentially unused parameter */
}


template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::print( ::std::ostream& os ) const
{
    m_addr_channel.print(os);
    m_data_channel.print(os);
}

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline void axi_read_channel<A, D, ARU, RU, ID, IDW>::dump( ::std::ostream& os ) const
{

}

template <class A, class D, class ARU, class RU, class ID, unsigned IDW>
inline ::std::ostream& operator << ( ::std::ostream& os, const axi_read_channel<A, D, ARU, RU, ID, IDW>& a )
{
    a.print( os );
    return os;
}

template <class A, class D, class ARU = std::monostate, class RU = std::monostate, class ID = _axiIdT, unsigned IDW = 4>
using axi_read_out = sc_port<axi_read_out_if<A, D, ARU, RU, ID, IDW> >;
template <class A, class D, class ARU = std::monostate, class RU = std::monostate, class ID = _axiIdT, unsigned IDW = 4>
using axi_read_in = sc_port<axi_read_in_if<A, D, ARU, RU, ID, IDW> >;

#endif // AXI_READ_CHANNEL_H
