#!/usr/bin/env python3

import argparse
import os
import re
import sys


MODULE_NAME = r"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*"
MODULE_DECL_RE = re.compile(rf"^\s*export\s+module\s+({MODULE_NAME})\s*;")
IMPORT_RE = re.compile(rf"^\s*(?:export\s+)?import\s+({MODULE_NAME})\s*;")


def scan_module(path):
    module_name = None
    imports = list()
    with open(path, "r", encoding="utf-8", errors="replace") as source:
        for line_number, line in enumerate(source, start=1):
            declaration = MODULE_DECL_RE.match(line)
            if declaration:
                if module_name is not None:
                    raise ValueError(
                        f"{path}:{line_number}: multiple exported module declarations"
                    )
                module_name = declaration.group(1)
                continue

            imported = IMPORT_RE.match(line)
            if imported and imported.group(1) not in imports:
                imports.append(imported.group(1))

    if module_name is None:
        # A .cppm without an `export module` declaration provides no module, so
        # it contributes nothing to the provider/import map: skip it with a
        # warning instead of failing the whole scan. Erroring here would poison
        # every make target that merely parses this makefile (the empty-scaffold
        # wedge: freshly `newmodule`-scaffolded units are empty until `make gen`
        # fills them). A genuinely missing module still surfaces later, when the
        # compiler cannot resolve an importer's `import`.
        print(
            f"gen_cpp_module_map.py: warning: {path}: "
            "no 'export module <name>;' declaration; skipping",
            file=sys.stderr,
        )
        return None

    return module_name, imports


def render_module_map(paths):
    modules = list()
    providers = dict()
    for path in sorted(os.path.normpath(path) for path in paths):
        scanned = scan_module(path)
        if scanned is None:
            continue
        module_name, imports = scanned
        if module_name in providers:
            raise ValueError(
                f"module {module_name!r} is provided by both "
                f"{providers[module_name]!r} and {path!r}"
            )
        providers[module_name] = path
        modules.append((module_name, path, imports))

    lines = [
        "# Generated by gen_cpp_module_map.py. Do not edit.",
        f"CPP_MODULE_NAMES := {' '.join(module[0] for module in modules)}",
    ]
    for module_name, path, imports in modules:
        lines.append(f"CPP_MODULE_PROVIDER_{module_name} := {path}")
        lines.append(
            f"CPP_MODULE_IMPORTS_{module_name} := {' '.join(imports)}"
        )
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path, content):
    try:
        with open(path, "r", encoding="utf-8") as existing:
            if existing.read() == content:
                return
    except FileNotFoundError:
        pass

    os.makedirs(os.path.dirname(path), exist_ok=True)
    temporary = f"{path}.tmp"
    with open(temporary, "w", encoding="utf-8") as output:
        output.write(content)
    os.replace(temporary, path)


def main(argv):
    parser = argparse.ArgumentParser(
        description="Scan C++20 module providers and imports into a Make include"
    )
    parser.add_argument("sources", nargs="*", help="C++ module interface sources")
    parser.add_argument("--output", required=True, help="Make include to write")
    args = parser.parse_args(argv)

    try:
        write_if_changed(args.output, render_module_map(args.sources))
    except (OSError, ValueError) as error:
        print(f"gen_cpp_module_map.py: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
