"""Post-database orphan sweep: delete the generated files a legacy fileMap
placed that the current authoring format no longer wants on disk (the includes
header->cppm and block-base header->cppm migrations leave such orphans behind,
and F10 retired the project-wide `vl_wrap.*` aggregate).

Unlike the other migration modules (migrateIncludes, migrateAddressControl,
migrateLayout) this one is NOT text-only and does not run before the database.
Expanding the legacy fileMap to concrete paths needs the current design
database, so this module runs POST-`make db`, against a read-only `projectOpen`
handle, and is driven by `migrateYaml.py --sweep --db <project.db>` as the
db->gen orphan-sweep step of the `make migrate` pipeline.

Sweep model (dispatch on the legacy fileMap's per-entry `migrate:` disposition):
  - `delete`  purely-generated legacy artifacts (context includes, block base,
              SV package, the HDL wrappers, tandem). Expanded over the current DB
              and swept: wiped now, regenerated by the following `make gen`.
  - `port`    user code the migration will later convert in place (`block`,
              `rtlModule`); NEVER expanded for deletion, so unreachable here.
  - `leave`   user testbench code (`testBench`, `tbConfig`, `tbExternal`); NEVER
              expanded for deletion.
The MAP is the decider: only `delete`-disposition entries (plus the explicit
LEGACY_LITERAL_DELETE aggregates, which no fileMap entry produces) become delete
targets. There is no `L\\C` set-difference; disposition alone drives the sweep.

Every delete target must carry the GENERATED_CODE marker (a name-matched file
without it is REPORTED as a manual TODO, never deleted) and is removed with a
plain filesystem delete (never `git rm`). User `#include` sites of a deleted
header are handed to the operator as manual TODOs. The sweep is delete-only; the
operator runs `make gen` afterwards to recreate the current-format artifacts.
"""

import os
from dataclasses import dataclass, field

from pysrc.migrateCommon import _isGenerated
from pysrc.migrateIncludes import _userIncludeSites
from pysrc.processYaml import expandNewModulePath, fileMapCondMatch


# ---------------------------------------------------------------------------
# Embedded legacy fileMap (authoritative copy)
# ---------------------------------------------------------------------------
# Captured verbatim from git (base config/project.yaml + pro/config/project.yaml
# at `main`, the pre-migration layout) so the sweep classifies against a FROZEN
# legacy map rather than the evolving merged map. Cross-checked against the
# feasibility summary; the only pro addition is the `tandem` entry.
#
# `basePath` values reference the current PROJECTLAYOUT segments (identical keys
# to the legacy `dirs:` below); files placed by the legacy map live under those
# same segment directories, so the legacy map expands correctly over the current
# layout. A legacy basePath absent from the current segments is skipped + reported
# rather than raising in expandNewModulePath.

# Legacy `dirs:` (base ⊕ pro). Embedded for documentation and the basePath guard;
# expansion uses the current PROJECTLAYOUT segments (same keys).
LEGACY_DIRS = {
    "base":    "$root/base",
    "model":   "$root/model",
    "rtl":     "$root/rtl",
    "vl_wrap": "$root/verif/vl_wrap",
    "tb":      "$root/tb",
    "fwInc":   "$root/fw/include",
}

# Per-entry `migrate:` disposition — the EXPLICIT DECIDER for the sweep (there is
# no L\C set-difference). Vocabulary:
#   `delete`  purely-generated legacy artifact; expanded over the current DB and
#             swept (wiped now, regenerated by the following `make gen`).
#   `port`    user code whose .cpp/.h->.cppm conversion is a later, agent-driven
#             step; NEVER expanded for deletion. The sweep only IDENTIFIES and
#             REPORTS an old-form file the current map now produces differently
#             (TODO_PORT); it never transforms or deletes it.
#   `leave`   user testbench code; never expanded, never touched.
MIGRATE_DELETE = "delete"
MIGRATE_PORT = "port"
MIGRATE_LEAVE = "leave"

# Legacy fileMap (base ⊕ pro). Each entry carries a `migrate:` disposition.
LEGACY_FILEMAP = {
    "blockBase":  {"name": "Base",            "ext": {"hdr": "h"},              "cond": {"hasMdl": True, "hasTb": True},                 "mode": "block",   "basePath": "base",    "migrate": MIGRATE_DELETE},
    "block":      {"name": "",                "ext": {"hdr": "h", "src": "cpp"}, "cond": {"hasMdl": True},                                "mode": "block",   "basePath": "model",   "migrate": MIGRATE_PORT},
    "rtlModule":  {"name": "",                "ext": {"sv": "sv"},              "cond": {"hasRtl": True},                                "mode": "block",   "basePath": "rtl",     "migrate": MIGRATE_PORT},
    "vlSvWrap":   {"name": "_hdl_sv_wrapper", "ext": {"sv": "sv"},              "cond": {"hasVl": True},                 "variant": True, "mode": "block",   "basePath": "vl_wrap", "migrate": MIGRATE_DELETE},
    "vlScWrap":   {"name": "_hdl_sc_wrapper", "ext": {"hdr": "h"},              "cond": {"hasVl": True},                                 "mode": "block",   "basePath": "vl_wrap", "migrate": MIGRATE_DELETE},
    "testBench":  {"name": "Testbench",       "ext": {"hdr": "h", "src": "cpp"}, "cond": {"hasTb": True}, "blockDir": True,               "mode": "block",   "basePath": "tb",      "migrate": MIGRATE_LEAVE},
    "tbConfig":   {"name": "Config",          "ext": {"src": "cpp"},            "cond": {"hasTb": True}, "blockDir": True,               "mode": "block",   "basePath": "tb",      "migrate": MIGRATE_LEAVE},
    "tbExternal": {"name": "External",        "ext": {"hdr": "h", "src": "cpp"}, "cond": {"hasTb": True}, "blockDir": True,               "mode": "block",   "basePath": "tb",      "migrate": MIGRATE_LEAVE},
    "include":    {"name": "Includes",        "ext": {"hdr": "h", "src": "cpp"}, "cond": {"smartInclude": True},                          "mode": "context", "basePath": "model",   "migrate": MIGRATE_DELETE},
    "package":    {"name": "_package",        "ext": {"sv": "sv"},              "cond": {"smartInclude": True},                          "mode": "context", "basePath": "rtl",     "migrate": MIGRATE_DELETE},
    # pro addition:
    "tandem":     {"name": "Tandem",          "ext": {"hdr": "h", "src": "cpp"}, "condAnd": {"hasMdl": True, "hasRtl": True},             "mode": "block",   "basePath": "base",    "migrate": MIGRATE_DELETE},
}

# Retired project-wide aggregates produced by NO fileMap entry (legacy or
# current), so fileMap expansion can never reach them. F10 retired the
# `vl_wrap.{cpp,h,sv}` project-wide verilation aggregate that lived at the
# `vl_wrap` segment. Listed as (segment, filename) and deleted like any other
# `delete` target (same _isGenerated marker guard, same missing-segment guard).
LEGACY_LITERAL_DELETE = [
    ("vl_wrap", "vl_wrap.cpp"),
    ("vl_wrap", "vl_wrap.h"),
    ("vl_wrap", "vl_wrap.sv"),
]


# Applied-edit kinds.
ORPHAN_DELETE = "ORPHAN_DELETE"              # generated orphan deleted

# Manual-TODO kinds (handed to the operator).
TODO_UNGENERATED_FILE = "TODO_UNGENERATED_FILE"  # delete-target name-match lacks the generated marker; not deleted
TODO_PORT = "TODO_PORT"                          # user-code file awaiting agent-driven .cpp/.h->.cppm port; not deleted
TODO_USER_INCLUDE = "TODO_USER_INCLUDE"          # user code #includes a deleted header
TODO_MISSING_BASEPATH = "TODO_MISSING_BASEPATH"  # legacy basePath absent from current layout; entry skipped
TODO_UNSUPPORTED_LAYOUT = "TODO_UNSUPPORTED_LAYOUT"  # context owner uses hierarchical layout; not swept


@dataclass(frozen=True)
class ReportItem:
    kind: str        # one of the kind constants above
    location: str    # file (or file:line) the item refers to
    message: str     # human-facing description


@dataclass
class OrphansReport:
    projectName: str
    applied: list = field(default_factory=list)   # list[ReportItem] (deletes)
    manual: list = field(default_factory=list)    # list[ReportItem]
    written: bool = False

    @property
    def clean(self):
        """True when nothing is left for the operator to resolve by hand."""
        return not self.manual


# ---------------------------------------------------------------------------
# DB-backed fileMap enumerator
# ---------------------------------------------------------------------------

def _layoutForContext(prj, context):
    return prj.projectLayout[prj.contextOwningProject[context]]


def _reconstructContexts(prj, report):
    """Recover, per valid context, its layout-resolved placement directory and
    the set of current context file types it is valid for — the projectOpen
    equivalent of projectCreate.includeValid, which is not persisted.

    The placement directory is derived from the persisted current placement
    (INCLUDEFILES) by inverting expandNewModulePath's functional join: it is a
    context property independent of file type, so any current context entry for
    the context recovers it. Validity is a database fact shared by every fileMap
    (a context is includable or not regardless of map), so the set of contexts a
    current context fileType produced is the set a legacy entry of that fileType
    would target. A context whose owning project uses hierarchical layout is
    reported and skipped: its node-relative segment cannot be inverted this way
    (hierarchical layout is a separate opt-in migration).
    """
    includeFiles = prj.config.getConfig("INCLUDEFILES")
    ctxDir = dict()          # context -> placement dir passed to expandNewModulePath
    validFor = dict()        # current fileType -> set(context)
    for fileType, fileDef in prj.filemap.items():
        if fileDef.get("mode", "block") != "context":
            continue
        basePath = fileDef["basePath"]
        for ext in fileDef["ext"]:
            expandedType = f"{fileType}_{ext}"
            if expandedType not in includeFiles:
                continue
            for context, entry in includeFiles[expandedType].items():
                layout = _layoutForContext(prj, context)
                if basePath not in layout["segments"]:
                    continue
                if layout["mode"] != "functional":
                    _reportUnsupportedLayout(report, context, layout["mode"])
                    continue
                segment = layout["segments"][basePath]["path"]
                ctxDir[context] = os.path.relpath(os.path.dirname(entry["fileName"]),
                                                  segment)
                validFor.setdefault(fileType, set()).add(context)
    return ctxDir, validFor


def _reportUnsupportedLayout(report, context, mode):
    if any(i.kind == TODO_UNSUPPORTED_LAYOUT and i.location == context
           for i in report.manual):
        return
    report.manual.append(ReportItem(
        TODO_UNSUPPORTED_LAYOUT, context,
        f"context '{context}' owner uses '{mode}' layout; its context orphans "
        f"are not swept (functional layout only)"))


def _condRow(prj, blockRow, blocksParams):
    # hasOwnParams (the block declares its own params:) is the one cond field not
    # stored on the block row; it is the block's own params: relationship.
    condData = dict(blockRow)
    condData["hasOwnParams"] = int(blockRow["blockKey"] in blocksParams)
    return condData


def expandFileMap(prj, fileMap, report):
    """Expand `fileMap` over the current DB to the concrete set of generated file
    paths (each expanded path with each declared extension).

    Reuses the map-agnostic primitives expandNewModulePath + fileMapCondMatch and
    iterates the same DB collections createBuildManifest.create iterates for block
    mode (prj.data['blocks']) and, for context mode, the reconstructed valid-
    context set (modelled on saveIncludeFiles). registrar- and project-mode
    entries are intentionally not enumerated: they emit only into the registrar /
    vl_wrap / project-root segments under names no legacy block/context entry
    produces, so they can neither appear in the legacy set nor match a legacy
    path, and thus are never delete targets. `report` collects missing-basePath
    guard notes.
    """
    blocksParams = {row["blockKey"] for row in prj.data["blocksparams"].values()}
    blockByKey = {row["blockKey"]: row for row in prj.data["blocks"].values()}
    paths = set()

    # block mode: one artifact per block per matching block-mode entry.
    for blockRow in blockByKey.values():
        condData = _condRow(prj, blockRow, blocksParams)
        layout = _layoutForContext(prj, blockRow["_context"])
        for fileType, fileDef in fileMap.items():
            if fileDef.get("mode", "block") != "block":
                continue
            if fileDef["basePath"] not in layout["segments"]:
                _reportMissingBasePath(report, fileType, fileDef["basePath"])
                continue
            if not fileMapCondMatch(fileDef, condData):
                continue
            filePath = expandNewModulePath(fileDef, blockRow["dir"],
                                           blockRow["block"], blockRow["block"],
                                           layout, missingDirOk=True)
            for ext in fileDef["ext"]:
                paths.add(filePath + "." + fileDef["ext"][ext])

    # context mode: expand each context entry over its valid contexts, mirroring
    # saveIncludeFiles (iterate valid contexts, resolve through expandNewModulePath).
    ctxDir, validFor = _reconstructContexts(prj, report)
    for fileType, fileDef in fileMap.items():
        if fileDef.get("mode", "block") != "context":
            continue
        for context in sorted(validFor.get(fileType, set())):
            layout = _layoutForContext(prj, context)
            if fileDef["basePath"] not in layout["segments"]:
                _reportMissingBasePath(report, fileType, fileDef["basePath"])
                continue
            includeName = prj.includeName[context]
            filePath = expandNewModulePath(fileDef, ctxDir[context],
                                           includeName, includeName,
                                           layout, missingDirOk=True)
            for ext in fileDef["ext"]:
                paths.add(filePath + "." + fileDef["ext"][ext])

    return paths


def _reportMissingBasePath(report, fileType, basePath):
    location = f"{fileType} (basePath: {basePath})"
    if any(i.kind == TODO_MISSING_BASEPATH and i.location == location
           for i in report.manual):
        return
    report.manual.append(ReportItem(
        TODO_MISSING_BASEPATH, location,
        f"legacy fileMap basePath '{basePath}' is absent from the current "
        f"project layout; entry '{fileType}' skipped"))


def _literalDeletePaths(prj, report):
    """Resolve LEGACY_LITERAL_DELETE (segment, filename) pairs against the current
    project layout. These aggregates are produced by no fileMap entry, so fileMap
    expansion can never reach them; they are named explicitly and swept under the
    same generated-marker and missing-segment guards as any delete target. A pair
    whose segment is absent from the current layout is reported and skipped.
    """
    segments = prj.projectLayout[prj.config.getConfig("PROJECTNAME")]["segments"]
    paths = set()
    for segment, fileName in LEGACY_LITERAL_DELETE:
        if segment not in segments:
            _reportMissingBasePath(report, f"literal:{fileName}", segment)
            continue
        paths.add(os.path.abspath(os.path.join(segments[segment]["path"], fileName)))
    return paths


# ---------------------------------------------------------------------------
# Sweep
# ---------------------------------------------------------------------------

def sweepOrphans(prj, write=False):
    """Compute and (when `write`) delete the legacy orphans of an opened project,
    DISPATCHING ON the embedded legacy fileMap's per-entry `migrate:` disposition.

    Delete targets are every `delete`-disposition legacy entry expanded over the
    current DB, unioned with the explicit LEGACY_LITERAL_DELETE aggregates.
    `port`/`leave` entries are never expanded, so they are unreachable for
    deletion by construction. A delete target that exists and carries the
    GENERATED_CODE marker is removed with a plain filesystem delete (never `git`);
    one that exists but lacks the marker is REPORTED, never deleted.

    `port` entries are only IDENTIFIED and REPORTED (TODO_PORT): an old-form user
    file present on disk that the current merged map now produces in a different
    form (e.g. a now-parameterized block whose current artifact is `.cppm`) awaits
    a later, agent-driven `.cpp/.h`->`.cppm` port. A same-form (non-parameterized)
    block is a no-op — nothing to port and nothing deleted. The sweep never
    transforms or deletes a `port` file. User `#include` sites of a deleted header
    are reported as manual TODOs. Delete-only: the caller runs `make gen` after.

    NOTE: the disposition is the sole delete decider; there is intentionally no
    `delete`-target-also-in-current-map cross-check. A project that overrode a
    `delete` entry (e.g. `include`) back to its legacy form would have those files
    swept — the _isGenerated marker guard is the only backstop for that case.
    """
    report = OrphansReport(projectName=prj.config.getConfig("PROJECTNAME"))

    deleteTargets = expandFileMap(prj, _dispositionMap(MIGRATE_DELETE), report)
    deleteTargets |= _literalDeletePaths(prj, report)

    deleted = list()
    for path in sorted(deleteTargets):
        if not os.path.exists(path):
            continue
        if not _isGenerated(path):
            report.manual.append(ReportItem(
                TODO_UNGENERATED_FILE, os.path.basename(path),
                f"delete target {os.path.basename(path)} has no generated marker; "
                f"left in place for manual review (not deleted)"))
            continue
        deleted.append(path)
        report.applied.append(ReportItem(
            ORPHAN_DELETE, os.path.basename(path),
            f"deleted legacy orphan {os.path.basename(path)}"))

    # port: identify old-form user files the current map now produces differently;
    # report for the later agent-driven port. Never expanded for deletion.
    portOldForm = expandFileMap(prj, _dispositionMap(MIGRATE_PORT), report)
    currentForm = expandFileMap(prj, prj.filemap, report)
    for path in sorted(portOldForm):
        if os.path.exists(path) and path not in currentForm:
            report.manual.append(ReportItem(
                TODO_PORT, os.path.basename(path),
                f"user-code file {path} awaits .cpp/.h->.cppm port; agent-driven, "
                f"do not delete"))

    # Hand-off: user code that #includes a deleted header must switch to the
    # current artifact (import <module>; for a migrated include/base, or the
    # sibling header for other classes). Reuses migrateIncludes._userIncludeSites.
    deletedHeaders = {os.path.basename(p) for p in deleted if p.endswith(".h")}
    if deletedHeaders:
        rootDir = prj.projectLayout[report.projectName]["segments"]["root"]["path"]
        projectData = {"dirs": {"root": "."}}
        for path, line in _userIncludeSites(rootDir, projectData, deletedHeaders):
            report.manual.append(ReportItem(
                TODO_USER_INCLUDE, f"{os.path.basename(path)}:{line}",
                f"user code #includes a deleted generated header; switch it to "
                f"the current artifact (import the module, or include its sibling)"))

    if write:
        for path in deleted:
            try:
                os.remove(path)
            except OSError as exc:
                raise RuntimeError(
                    f"orphan sweep: cannot delete legacy orphan "
                    f"{os.path.basename(path)}: {exc}")
        report.written = bool(deleted)

    return report


def _dispositionMap(disposition):
    """Subset of LEGACY_FILEMAP entries carrying `disposition`."""
    return {ft: fd for ft, fd in LEGACY_FILEMAP.items()
            if fd["migrate"] == disposition}


# ---------------------------------------------------------------------------
# Report rendering
# ---------------------------------------------------------------------------

def renderReport(report, write):
    """Render the sweep report as text."""
    lines = [f"=== orphan sweep: {report.projectName} ==="]
    if not report.applied and not report.manual:
        lines.append("  no legacy orphans; nothing to sweep")
        return "\n".join(lines)
    if report.applied:
        verb = "deleted" if write else "would delete (dry-run)"
        lines.append(f"  {verb}:")
        for item in report.applied:
            lines.append(f"    {item.location}  {item.kind}  {item.message}")
    if report.manual:
        lines.append("  manual TODO:")
        for item in report.manual:
            lines.append(f"    {item.location}  {item.kind}  {item.message}")
    if report.applied and not write:
        lines.append("  (dry-run; re-run with --write to delete, then run `make gen`)")
    elif report.applied and write:
        lines.append("  delete-only; run `make gen` to recreate current-format artifacts")
    return "\n".join(lines)
