# Per-top simulator boundary files for the HDL verification wrappers: the VCS
# `-sc_portmap` file and the Xcelium foreign-module shell header. Both need the
# evaluated width of every pin, so they are derived from the block view plus the
# per-top widths VLTOPS persisted at database creation, and written whole under
# .gen/vl like the build manifest: no user region, regenerated by `make gen`,
# and owned by whichever project's manifest lists the top.
import os
from pysrc.arch2codeHelper import printError, warningAndErrorReport


def vlBoundaryGen(prj, args):
    manifest = prj.config.getConfig('BUILDMANIFEST')
    outDir = os.path.join(prj.config.getConfig('DIRS')['root'], '.gen', 'vl')
    os.makedirs(outDir, exist_ok=True)
    for top in manifest['vlTops']:
        name = top['qualifiedTop']
        blockKey = prj.vlTops[name]['blockKey']
        data = prj.getBlockData(blockKey, trimRegLeafInstance=True)
        if not data:
            printError(f"vlBoundary: block '{blockKey}' of HDL top '{name}' is out of scope")
            exit(warningAndErrorReport())
        pins = prj.getVlTopBoundaryPins(data, name)
        with open(os.path.join(outDir, f'{name}.portmap'), 'w') as f:
            f.write(portmap(name, pins))
        with open(os.path.join(outDir, f'{name}_xcelium.h'), 'w') as f:
            f.write(xceliumShell(name, pins))


def portmap(top, pins):
    lines = [f'# Generated by arch2code (vlBoundary) for HDL top {top}. Do not edit.',
             '# name width HDL-type SystemC-type']
    for pin in pins:
        hdlType, scType = ('bit', 'bool') if pin['width'] == 1 else ('bitvector', 'sc_bv')
        lines.append(f"{pin['pin']} {pin['width']} {hdlType} {scType}")
    return '\n'.join(lines) + '\n'


def xceliumShell(top, pins):
    def scType(pin):
        return 'bool' if pin['width'] == 1 else f"sc_bv<{pin['width']}>"
    guard = f'{top.upper()}_XCELIUM_H_'
    out = [f'// Generated by arch2code (vlBoundary) for HDL top {top}. Do not edit.',
           f'#ifndef {guard}', f'#define {guard}', '', '#include "systemc.h"', '',
           f'class {top} : public xmsc_foreign_module {{', 'public:']
    for pin in pins:
        port = 'sc_in' if pin['direction'] == 'input' else 'sc_out'
        out.append(f"    {port}<{scType(pin)}> {pin['pin']};")
    inits = ', '.join(f"{pin['pin']}(\"{pin['pin']}\")" for pin in pins)
    out += ['',
            f'    explicit {top}(sc_module_name nm) : xmsc_foreign_module(nm), {inits} {{}}',
            f'    const char* hdl_name() const override {{ return "{top}"; }}',
            '};', '', f'#endif // {guard}']
    return '\n'.join(out) + '\n'
