
all:
	$(MAKE) -C blockA all
	$(MAKE) -C blockB all
	$(MAKE) -C apbDecode all
	$(MAKE) -C someRapper all

run:
	$(MAKE) -C blockA run
	$(MAKE) -C blockB run
	$(MAKE) -C apbDecode run
	$(MAKE) -C someRapper run

clean:
	$(MAKE) -C blockA clean
	$(MAKE) -C blockB clean
	$(MAKE) -C apbDecode clean
	$(MAKE) -C someRapper clean
