REPO_ROOT = $(shell git rev-parse --show-toplevel)/examples/mixed

include $(REPO_ROOT)/include/make/shared.mk

# Source directory for Verilator wrapper files
VL_SRC_DIRS = $(REPO_ROOT)/verif/vl_wrap

include $(A2C_ROOT)/include/make/a2c-vl-wrap.mk
