REPO_ROOT = $(shell git rev-parse --show-toplevel)/examples/hierVlDemo

include $(REPO_ROOT)/include/make/shared.mk

# Verilator wrapper source dirs (from manifest)
VL_SRC_DIRS = $(A2C_VL_WRAP_DIRS)

include $(A2C_ROOT)/include/make/a2c-vl-wrap.mk
