REPO_ROOT = /work/ws/debayer/builder/base/unittest/file_prefix_705eskao/ip

include $(REPO_ROOT)/include/make/shared.mk

.PHONY : clean

clean::
	rm -rf $(A2C_SQLDB_DOTFILE) $(A2C_SQLDB_FILE) $(GEN_BUILD_DIR)
