
#ifndef XPMTXTPLTOPVARIANTCONFIG_H_
#define XPMTXTPLTOPVARIANTCONFIG_H_
// 

// GENERATED_CODE_PARAM --project=xpMtxTpl --context=../../yaml/xpMtxTplTop.yaml
// GENERATED_CODE_BEGIN --template=config

// GENERATED_CODE_END

#endif //XPMTXTPLTOPVARIANTCONFIG_H_
