= Block Diagram of an example architecture named *mixed*

The name *mixed* is used for this example because it is used to generate both SystemC and SystemVerilog outputs. 
Below are diagrams representing this mixed example. The first diagram, <<humanDrawn>>, is drawn by a human and the 
second, <<depth3>>, is a diagram generated by arch2code.

.A Human Drawn Diagram
image::mixed.svg[width=3072,id=humanDrawn]

When arch2code generates a diagram those diagram(s) have more detail embeded in tooltips. Arch2code trys to keep 
the diagram clean but add as much detail from the architecture definition as possible. This is why a lot of 
information is put into the tooltips.

*Tooltip Example:* the interface from `blockA` to `blockD` says _aStuffIf(aSt, aASt) An interface for A_. 
The `aStuffIf` portion is the interface name. The `aSt` and `aASt` are structures used on that interface and 
`An interface for A` is the description of that interface. All definitions are from the *SSoT* and generated in 
the images below, e.g. <<depth3>>.

*Tooltip Example2:* the interface from `apbDecode` to `blockB` says _apbIf(apbAddrSt, apbDataSt) CPU access to 
SoC registers in the design_. Similarly to the previous example, the `abpIf` portion is the interface name. 
The `apbAddrSt` and `apbDataSt` are the structures used on that interface and `CPU access to SoC registers in the 
design` is the desciption of that interface. Again all these definitions are from the *SSoT*.

This mixed example has been used to generate `SystemC` and `SystemVerilog` designs. See the directory 
`examples/mixed/model` for the `SystemC` design. The directory is relative to the root of the repository. 
The build target in the top level `Makefile` called `systemc-mixed` and it illustrates how a systemC model is built. 
Setup of a systemC model will be covered later. For the `SystemVerilog` output check the direcotry `examples/mixed
/systemVerilog`. The build target `lint-mixed` in the top level `Makefile` lead you to how it is built and linted.

The input *SSoT* for this mixed example can be found starting in the `examples/mixed/arch/mixedProject.yaml` file. 
This file is relative to the root of the https://bitbucket.org/arch2code/arch2code/src/main/[code repository]. 
Notice that in this mixed example `blockC` is treated as an external IP (intelectual property) that is inlucded 
into the main project. This is an example of how an architecture can be broken down or built by more than one engineer 
or group of engineers.

.Diagram Drawn by arch2code
image::uTopDepth3.svg[width=3072,opts=interactive,id=depth3]

The <<depth3>> can be made with the following commands. These should be run from the root of the repository.
[bash]
----
./arch2code.py --yaml examples/mixed/arch/mixedProject.yaml
./arch2code.py -r --diagram --depth 3
----
The output file is located at:
[bash]
----
gv_out/mixed.gv.svg
----

Arch2code can also draw any structure within the design for documentation. Two examples are shown below <<aSt>> and 
<<nestedSt>>. Mouse over the interface in <<depth3>> out of `blockA` into `blockD` to see that <<aSt>> is being used 
on that interface.

.aSt Diagram
image::aSt.svg[opst=interactive,id=aSt]

Notice that <<aSt>> has a 2 member array of `variablea`.

.nestedSt Diagram
image::nestedSt.svg[id=nestedSt]

The `nestedSt` has four members; variablea (two bits), bob (of type dSt), joe[2] (of type seeSt). Some might think 
joe should be joe[1:0]. 
The <<nestedSt>> can be made with the following commands. These commands should be run from the root of the repository.
[bash]
----
./arch2code.py --yaml examples/mixed/arch/mixedProject.yaml
./arch2code.py -r --drawStructure nestedSt/mixed.yaml
----
The output file is located at:
[bash]
----
gv_out/mixed.gv.svg
----

A <<nestedStWhite>> can be created with the following commands.
[bash]
----
./arch2code.py --yaml examples/mixed/arch/mixedProject.yaml
./arch2code.py -r --drawStructure nestedSt/mixed.yaml --colors white
----
The output file is located at:
[bash]
----
gv_out/mixed.gv.svg
----

.nestedSt Diagram less color
image::nestedStWhite.svg[id=nestedStWhite]

More on block diagrams, for illustrative purposes the followng two diagrams can also be generated at the same time as the 
depth 3 diagram which contains the entire architecutre.

The <<depth2>> can be made with the following commands.
[bash]
----
./arch2code.py --yaml examples/mixed/arch/mixedProject.yaml
./arch2code.py -r --diagram --depth 2
----
The output file is located at:
[bash]
----
gv_out/mixed.gv.svg
----

Similarly, <<depth1>> can be made with the following commands.
[bash]
----
./arch2code.py --yaml examples/mixed/arch/mixedProject.yaml
./arch2code.py -r --diagram --depth 1
----
The output file is located at:
[bash]
----
gv_out/mixed.gv.svg
----

Note: that if these commands are run in series the `--yaml` option and the project file only need to be run once. 
You can also use the options `--diagramOutFileName` and `--diagramOutDirectory` to set the output location of the 
`svg` file.

.mixed Diagram with a hierarchy Depth of 2
image::uTopDepth2.svg[width=3072,opts=interactive,id=depth2]

.mixed Diagram with a hierarchy Depth of 1
image::uTopDepth1.svg[width=3072,opts=interactive,id=depth1]
