templates:
  classDecl: $a2c/templates/systemc/classDecl.py
  baseClassDecl: $a2c/templates/systemc/baseClassDecl.py
  constructor: $a2c/templates/systemc/constructor.py
  baseConstructor: $a2c/templates/systemc/baseConstructor.py
  blockRegs: $a2c/templates/systemc/blockRegs.py
  headers: $a2c/templates/systemc/headers.py
  includes: $a2c/templates/systemc/includes.py
  structures: $a2c/templates/systemc/structures.py
  encoder: $a2c/templates/systemc/encoder.py
  module_hdl_sc_wrapper: $a2c/templates/systemc/module_hdl_wrapper.py
  tbExternal: $a2c/templates/systemc/testbench.py
  tbConfig: $a2c/templates/systemc/testbench.py
  testbench: $a2c/templates/systemc/testbench.py
