import os

import pysrc.arch2codeGlobals as g
import pysrc.artifactPaths as artifactPaths
import pysrc.migrateCommon as migrateCommon
from pysrc.arch2codeHelper import printWarning

# Generated-source toolchain split, mirroring the make find globs: the C++ build
# consumes .cpp/.h/.cppm, the SystemVerilog/verilator build consumes .sv/.svh.
# rtl.f (ext 'f') is a file list, not a compiled source, so it is in neither set.
_CPP_GEN_EXTS = {'cpp', 'h', 'cppm'}
_SV_GEN_EXTS = {'sv', 'svh'}


def _writeBuildManifestMk(rootDir, manifest):
    genDir = os.path.join(rootDir, '.gen')
    os.makedirs(genDir, exist_ok=True)

    def asList(paths):
        return ' '.join(paths)

    lines = [
        "# Generated by arch2code projectCreate (buildManifest). Do not edit.",
        "# Derived build directory/file set for this project's layout; see",
        "# plan-decomp-functional-layout.md (Q-L2 / L2a).",
        f"A2C_MANIFEST_LAYOUT := {manifest['mode']}",
        f"A2C_YAML_FILES := {asList(manifest['yamlFiles'])}",
        f"A2C_SC_SRC_DIRS := {asList(manifest['scSrcDirs'])}",
        f"A2C_SV_SRC_DIRS := {asList(manifest['svSrcDirs'])}",
        f"A2C_VL_WRAP_DIRS := {asList(manifest['vlWrapDirs'])}",
        f"A2C_CPP_MODULE_FILES := {asList(manifest['cppModuleFiles'])}",
        f"A2C_SV_FILES := {asList(manifest['svFiles'])}",
        f"A2C_SV_DEP_FILES := {asList(manifest['svDepFiles'])}",
        f"A2C_SC_GEN_FILES := {asList(manifest['scGenFiles'])}",
        f"A2C_SV_GEN_FILES := {asList(manifest['svGenFiles'])}",
        f"A2C_RTL_DOT_F := {manifest['rtlDotF']}",
        f"A2C_VL_TOPS := {asList([t['qualifiedTop'] for t in manifest['vlTops']])}",
    ]
    # DUT-top wrapper per HDL top block, keyed by block name: the wrapper of that
    # block's top instance at its resolved variant. The lint makefile looks this
    # up by HDL_TOP_MODULE (A2C_VL_TOP_<block>) to name exactly one --top-module,
    # unambiguous under multiple variants, prefix-sharing siblings, or several
    # Verilated top-level children.
    for block in sorted(manifest['dutTops']):
        lines.append(f"A2C_VL_TOP_{block} := {manifest['dutTops'][block]}")
    # Per-top verilated-wrapper records: the physical .sv wrapper keyed by the
    # unique design-unit name, so a2c-vl-wrap.mk consumes the DB-derived wrapper
    # path directly instead of deriving tops from filenames. The verilator object
    # name, generated header, include search path, and build-output directory are
    # tool/layout conventions reconstructed in the make infrastructure, not
    # manifest facts.
    for top in manifest['vlTops']:
        name = top['qualifiedTop']
        lines.append(f"A2C_VL_SV_{name} := {top['physicalSv']}")
    lines.append("")
    with open(os.path.join(genDir, 'build.mk'), 'w') as f:
        f.write('\n'.join(lines))


def create(prj):
    # Derive the per-project build directory/file set from the same emission
    # decisions the file generator makes. The manifest uses the persisted layout
    # so artifact placement and build grouping share one project-create contract.
    fileMap = prj.proj['fileGeneration']['fileMap']
    # Per-owning-project layouts. Object placement is resolved under the layout
    # of the project that owns the object's defining context, so a child-owned
    # artifact lands in the child project's segments. The root layout supplies
    # the build-group buckets and the project-scoped verilator wrapper segment.
    projectLayout = prj.config.getConfig('PROJECTLAYOUT')
    rootProject = prj.config.getConfig('PROJECTNAME')
    rootLayout = projectLayout[rootProject]

    dirs = {group: set() for group in rootLayout['buildGroups']}
    moduleFiles = set()
    svModuleFiles = set()
    # SV wrapper bodies reached only by `include`. No command line names them, so
    # they are dependencies of the owning block's tops but never compile inputs.
    svWrapBodies = set()
    # Complete generated-file enumeration split by toolchain. Every file the
    # generator emits is recorded here so the makefiles consume the DB-derived
    # set instead of rediscovering GENERATED-marked files on disk.
    scGenFiles = set()
    svGenFiles = set()

    blocksParams = {row['blockKey'] for row in prj.flatData['blocksparams'].values()}
    blockByKey = {row['blockKey']: row for row in prj.flatData['blocks'].values()}

    # Restrict the managed SV compile set to this build's design hierarchy. A
    # referenced child project's standalone harness (e.g. a reusable IP's own
    # ipStdTop verification top) is parsed into the same database but is not
    # contained by this build's topInstance; its modules import that harness
    # context's package, which the reachability-scoped rtl.f (correctly) does not
    # list, so verilating them here fails with an unresolved package import.
    # Scoping svModuleFiles to reachable blocks keeps A2C_SV_FILES aligned with
    # rtl.f. For a single-project build every block is reachable and this is a
    # no-op.
    #
    # Project creation persists the active instance set before artifact
    # derivation. Convert that set to blocks without repeating containment.
    reachableInstances = prj.config.getConfig('REACHABLEINSTANCES')
    reachableBlockKeys = set()
    for instanceKey, instRow in prj.flatData['instances'].items():
        if instanceKey not in reachableInstances:
            continue
        reachableBlockKeys.add(instRow['instanceTypeKey'])
        if instRow['containerKey'] in blockByKey:
            reachableBlockKeys.add(instRow['containerKey'])

    def layoutForContext(context):
        return projectLayout[prj.contextOwningProject[context]]

    def condRow(blockRow):
        # hasOwnParams is the block's own params: relationship, the one cond
        # field not stored on the block row.
        condData = dict(blockRow)
        condData['hasOwnParams'] = int(blockRow['blockKey'] in blocksParams)
        return condData

    def record(fileDef, filePath, objLayout, rootOwnedGen, svCompile=True):
        role = objLayout['segments'][fileDef['basePath']]['buildGroup']
        if role is None:
            return
        dirs[role].add(os.path.dirname(filePath))
        # Gen targets are owned-only: only artifacts whose generation this
        # build-root project owns are enumerated for (re)generation, so a build
        # never spawns no-op arch2code --file invocations against a foreign
        # sub-project's sources. The module/compile sets below (moduleFiles,
        # svModuleFiles) and dirs stay foreign-inclusive so foreign artifacts
        # still COMPILE without being regenerated here.
        if rootOwnedGen:
            for extVal in fileDef['ext'].values():
                genFile = filePath + '.' + extVal
                if extVal in _CPP_GEN_EXTS:
                    scGenFiles.add(genFile)
                elif extVal in _SV_GEN_EXTS:
                    svGenFiles.add(genFile)
        if 'cppm' in fileDef['ext']:
            moduleFiles.add(filePath + '.' + fileDef['ext']['cppm'])
        # Explicit managed SV module files. role=='sv' selects rtlModule and
        # excludes the vl_wrap wrappers (buildGroup vl); packages (context mode)
        # are listed separately by the rtl.f template, not here. svCompile gates
        # out blocks outside this build's design hierarchy (a referenced child's
        # standalone harness) so the compile set matches the reachability-scoped
        # rtl.f.
        if svCompile and 'sv' in fileDef['ext'] and role == 'sv':
            svModuleFiles.add(filePath + '.' + fileDef['ext']['sv'])
        if role == 'vl' and 'svh' in fileDef['ext']:
            svWrapBodies.add(filePath + '.' + fileDef['ext']['svh'])

    # block mode: one artifact per block per matching block-mode entry.
    for blockRow in blockByKey.values():
        condData = condRow(blockRow)
        objLayout = layoutForContext(blockRow['_context'])
        rootOwnedGen = prj.contextOwningProject[blockRow['_context']] == rootProject
        for fileDef in fileMap.values():
            if fileDef.get('mode', 'block') != 'block':
                continue
            if not artifactPaths.fileMapCondMatch(fileDef, condData):
                continue
            filePath = artifactPaths.expandNewModulePath(fileDef, blockRow['dir'],
                                                         blockRow['block'], blockRow['block'],
                                                         objLayout, missingDirOk=True)
            record(fileDef, filePath, objLayout, rootOwnedGen,
                   svCompile=blockRow['blockKey'] in reachableBlockKeys)

    # registrar mode: one trampoline per assembler per distinct matching child it
    # instantiates, under the assembler's directory.
    registrarMap = {k: v for k, v in fileMap.items()
                    if v.get('mode', 'block') == 'registrar'}
    blockRegistrarMap = {k: v for k, v in registrarMap.items()
                         if not v.get('foreignConfig', False)
                         and not v.get('pairVlTop', False)}
    foreignRegistrarMap = {k: v for k, v in registrarMap.items()
                           if v.get('foreignConfig', False)}
    # foreignConfig: true marks two artifact families; the variant: flag tells them apart.
    configModuleRegistrarMap = {k: v for k, v in foreignRegistrarMap.items()
                               if not v.get('variant', False)}
    pairVlRegistrarMap = {k: v for k, v in registrarMap.items()
                          if v.get('pairVlTop', False)}
    if registrarMap:
        registrarPairs = prj.config.getConfig('REGISTRARPAIRS')
        for assemblerKey, childKey in sorted(registrarPairs):
            assemblerDir = blockByKey[assemblerKey]['dir']
            # The trampoline is parent-owned: it lands under the assembler's
            # directory, so it resolves under the assembler project layout.
            objLayout = layoutForContext(blockByKey[assemblerKey]['_context'])
            childRow = blockByKey[childKey]
            childCond = condRow(childRow)
            pair = registrarPairs[(assemblerKey, childKey)]
            for fileDef in blockRegistrarMap.values():
                if not artifactPaths.fileMapCondMatch(fileDef, childCond):
                    continue
                if fileDef.get('requiresRegistrations', False) \
                        and not pair['aggregateHasModelRegistrations']:
                    continue
                filePath = artifactPaths.expandNewModulePath(
                    fileDef, assemblerDir, childRow['block'],
                    pair['artifactStem'], objLayout, missingDirOk=True)
                # Registrar trampolines are generated by the owning assembler's
                # project (here, the build root), so they stay in the gen set
                # even though they reference a foreign child.
                record(fileDef, filePath, objLayout, True)

        # CONFIGMODULES is computed under the same emit gate the config emitter
        # uses, so manifest and emitter agree.
        for (owner, childKey), entry in sorted(prj.config.getConfig('CONFIGMODULES').items()):
            childRow = blockByKey[childKey]
            childCond = condRow(childRow)
            parentRow = blockByKey[entry['parentKey']]
            objLayout = layoutForContext(parentRow['_context'])
            for fileDef in configModuleRegistrarMap.values():
                if not artifactPaths.fileMapCondMatch(fileDef, childCond):
                    continue
                filePath = artifactPaths.expandNewModulePath(fileDef, parentRow['dir'],
                                                             childRow['block'], entry['stub'],
                                                             objLayout, missingDirOk=True)
                record(fileDef, filePath, objLayout, owner == rootProject)

        # A generated file in an owned registrar directory that the contract does
        # not name is stale. Warn here; newmodule performs the deletion.
        registrarFiles, registrarDirs = artifactPaths.getStaleSegmentFiles(
            prj, {blockKey: condRow(row) for blockKey, row in blockByKey.items()},
            fileMap, 'registrar')
        generatedInDirs, _ = migrateCommon.classifyGeneratedDir(registrarDirs)
        staleRegistrarFiles = sorted(set(generatedInDirs) - registrarFiles)
        for staleFile in staleRegistrarFiles:
            printWarning(f"stale registrar file {staleFile} is not part of "
                        f"this project's current registrar contract")
        if staleRegistrarFiles:
            printWarning("run 'make newmodule' to remove stale registrar files")

    # A generated file in an owned vl_wrap directory that the contract does not
    # name is stale (left behind by a block/variant rename). Warn here;
    # newmodule performs the deletion.
    vlWrapFiles, vlWrapDirs = artifactPaths.getStaleSegmentFiles(
        prj, {blockKey: condRow(row) for blockKey, row in blockByKey.items()},
        fileMap, 'vl_wrap')
    generatedInDirs, _ = migrateCommon.classifyGeneratedDir(vlWrapDirs)
    staleVlWrapFiles = sorted(set(generatedInDirs) - vlWrapFiles)
    for staleFile in staleVlWrapFiles:
        printWarning(f"stale vl_wrap file {staleFile} is not part of "
                    f"this project's current verification-wrapper contract")
    if staleVlWrapFiles:
        printWarning("run 'make newmodule' to remove stale verification-wrapper files")

    # context mode: reuse the paths saveIncludeFiles already resolved through
    # the path seam, with validity/smartInclude already applied.
    includeFiles = prj.config.getConfig('INCLUDEFILES')
    for fileType, fileDef in fileMap.items():
        if fileDef.get('mode', 'block') != 'context':
            continue
        for ext in fileDef['ext']:
            expandedType = f"{fileType}_{ext}"
            if expandedType not in includeFiles:
                continue
            # Each include entry is keyed by its context file; resolve its build
            # role under the owning project's layout (path already resolved
            # through that layout in saveIncludeFiles).
            for context, entry in includeFiles[expandedType].items():
                role = layoutForContext(context)['segments'][fileDef['basePath']]['buildGroup']
                if role is None:
                    continue
                dirs[role].add(os.path.dirname(entry['fileName']))
                extVal = fileDef['ext'][ext]
                # Owned-only gen: refresh a context's generated source only when
                # this build-root project owns the context. Foreign contexts still
                # land in moduleFiles/dirs so they COMPILE but are never
                # regenerated by this project's gen.
                if prj.contextOwningProject[context] == rootProject:
                    if extVal in _CPP_GEN_EXTS:
                        scGenFiles.add(entry['fileName'])
                    elif extVal in _SV_GEN_EXTS:
                        svGenFiles.add(entry['fileName'])
                if ext == 'cppm':
                    moduleFiles.add(entry['fileName'])

    # project mode: exactly one artifact per project at its basePath segment
    # root, keyed to the top context (mirrors the newModule project scaffold).
    # A definitions-only project (no top context) emits none; the ownership gate
    # keeps a composed build from recording a referenced child project's copy.
    # Layout-correct path of the per-project rtl.f verilator file list. Published
    # so the shared VL/lint makefiles consume it instead of assuming the
    # functional $root/rtl/rtl.f, which is wrong for a hierarchical multi-node
    # top whose rtl segment lives under <topNode>/rtl. Empty for a definitions-
    # only project (no top context, emits no rtl.f).
    rtlDotFPath = ''
    topContext = prj.config.getConfig('TOPCONTEXT')
    if topContext is not None and prj.contextOwningProject[topContext] == prj.config.getConfig('PROJECTNAME'):
        objLayout = layoutForContext(topContext)
        # In hierarchical layout the per-project artifact anchors to the top
        # context's node directory (the top block's persisted node dir) so its
        # node-relative segment resolves inside the project tree, matching where
        # the newModule scaffold writes it. Functional layout uses $root-
        # absolute segments and needs no node anchor.
        if objLayout['mode'] == 'hierarchical':
            topBlockKey = next(inst['instanceTypeKey']
                               for inst in prj.flatData['instances'].values()
                               if inst['container'] == '_topInstance')
            nodeDir = blockByKey[topBlockKey]['dir']
        else:
            nodeDir = ''
        for fileType, fileDef in fileMap.items():
            if fileDef.get('mode', 'block') != 'project':
                continue
            filePath = artifactPaths.expandNewModulePath(fileDef, nodeDir, '', '', objLayout, missingDirOk=True)
            # Project-mode artifacts are reached only when the root owns the top
            # context (gated above), so they are always root-owned gen targets.
            record(fileDef, filePath, objLayout, True)
            # The rtl.f file list is resolved through the same emit seam as every
            # other project-mode artifact, so its path is layout-correct in both
            # functional ($root/rtl/rtl.f) and hierarchical (<topNode>/rtl/rtl.f).
            if fileType == 'rtlDotF':
                rtlDotFPath = filePath + '.' + fileDef['ext']['f']

    # Per-top verilated-wrapper records: the explicit (physical .sv -> design
    # unit) set the verilator wrap build consumes, so a2c-vl-wrap.mk names each
    # --top and its physical wrapper directly rather than deriving them from
    # filenames or globbing. The set mirrors the emitted vl-role .sv wrappers:
    # block-mode vlSvWrap (one per variant for a parameterizable block, one bare
    # otherwise; the .svh body is never a top) and registrar-mode vlSvWrapForeign
    # (one owner-qualified top per foreign variant). The design-unit name is the
    # file basename (moduleFileStub + fileMap 'name') -- the same composition the
    # SV wrapper view emits -- so the record and the emitted module name agree.
    vlTops = list()

    def recordVlTop(fileDef, filePath, qualifiedTop=None):
        vlTops.append({
            'physicalSv':   filePath + '.' + fileDef['ext']['sv'],
            'qualifiedTop': qualifiedTop or os.path.basename(filePath),
        })

    def isVlSvTop(fileDef, objLayout):
        # A verilated top is a vl-buildGroup .sv wrapper. The .svh body
        # (vlSvWrapBody) and the SC wrapper (vlScWrap, .h) are excluded here.
        if 'sv' not in fileDef['ext']:
            return False
        return objLayout['segments'][fileDef['basePath']]['buildGroup'] == 'vl'

    # Same-project variant labels per block. A foreign variant (declaring project
    # != the block's config-context owner) is emitted as a registrar-mode
    # owner-qualified top (vlSvWrapForeign), not a block-mode wrapper, so it is
    # excluded here -- mirroring the config emit gate in calcForeignConfigHeaders.
    blockVariants = {
        blockKey: {descriptor['variant'] for descriptor in descriptors
                   if not descriptor['isForeign']
                   and not descriptor['containerSourced']}
        for blockKey, descriptors
        in prj.config.getConfig('VARIANTCONFIGDESCRIPTORS').items()}

    # DUT-top candidates: the HDL top the lint/vl build drives is named by
    # HDL_TOP_MODULE, which is either the design top block itself (when
    # Verilated) or one of its direct children (a testbench harness wrapping a
    # Verilated DUT). Each candidate maps its block key to that instance's
    # resolved variant, so the wrapper recorded below is the single top for that
    # block -- not every declared variant. The lint makefile then looks up
    # HDL_TOP_MODULE by exact block name (A2C_VL_TOP_<block>) instead of
    # prefix-matching A2C_VL_TOPS, which is ambiguous once the top block declares
    # several variants, a Verilated sibling shares its name prefix, or several
    # direct children are Verilated.
    dutTopVariantByBlock = dict()
    topInst = next((inst for inst in prj.flatData['instances'].values()
                    if inst['container'] == '_topInstance'), None)
    if topInst is not None:
        topBlockKey = topInst['instanceTypeKey']
        dutInsts = list()
        if blockByKey[topBlockKey]['hasVl']:
            dutInsts.append(topInst)
        dutInsts += [inst for inst in prj.flatData['instances'].values()
                     if inst['containerKey'] == topBlockKey
                     and blockByKey[inst['instanceTypeKey']]['hasVl']]
        for inst in dutInsts:
            dutTopVariantByBlock[inst['instanceTypeKey']] = inst['variant'] or ''

    dutTops = dict()
    for blockRow in blockByKey.values():
        condData = condRow(blockRow)
        objLayout = layoutForContext(blockRow['_context'])
        for fileDef in fileMap.values():
            if fileDef.get('mode', 'block') != 'block':
                continue
            if not isVlSvTop(fileDef, objLayout):
                continue
            if not artifactPaths.fileMapCondMatch(fileDef, condData):
                continue
            block = blockRow['block']
            # A block reached only through inheritContainerParam declares no
            # variant anything selects; its tops are built at its container's.
            variants = sorted({v for source in prj.variantSourceBlocks[blockRow['blockKey']]
                               for v in blockVariants.get(source, set())})
            if condData['hasOwnParams'] and not variants:
                # Every declared variant is container-sourced, so this block has
                # no standalone top; the pair loop below records its verilated
                # top against the same physical file.
                continue
            variantStubs = [(v, f'{block}_{v}') for v in variants] \
                if (fileDef.get('variant', False) and variants) else [('', block)]
            for variant, stub in variantStubs:
                filePath = artifactPaths.expandNewModulePath(fileDef, blockRow['dir'],
                                                             block, stub, objLayout,
                                                             missingDirOk=True)
                recordVlTop(fileDef, filePath)
                # Capture a DUT-top wrapper name from the same emission that
                # records it (so the map and A2C_VL_TOPS agree exactly), keyed by
                # block name for the makefile's HDL_TOP_MODULE lookup.
                if dutTopVariantByBlock.get(blockRow['blockKey']) == variant:
                    dutTops[block] = os.path.basename(filePath)

    if foreignRegistrarMap:
        # A foreign owner-qualified top is a build artifact the reused child's
        # VlRegistrar (in the declaring project) instantiates. A composed build
        # runs ONE vl_wrap build for the whole assembled tree, so it must
        # verilate every foreign top present -- including one owned by a
        # sub-project (its .sv is scaffolded under that sub-project by its own
        # newmodule). The pair set is already owner-qualified and deduped.
        for (owner, childKey), entry in sorted(prj.config.getConfig('FOREIGNCONFIGHEADERS').items()):
            childRow = blockByKey[childKey]
            childCond = condRow(childRow)
            parentRow = blockByKey[entry['parentKey']]
            objLayout = layoutForContext(parentRow['_context'])
            for fileDef in foreignRegistrarMap.values():
                if not isVlSvTop(fileDef, objLayout):
                    continue
                if not artifactPaths.fileMapCondMatch(fileDef, childCond):
                    continue
                for variant in entry['vlVariants']:
                    filePath = artifactPaths.expandNewModulePath(
                        fileDef, parentRow['dir'], childRow['block'],
                        f"{entry['stub']}_{variant}", objLayout, missingDirOk=True)
                    recordVlTop(fileDef, filePath)

    if pairVlRegistrarMap:
        registrarPairs = prj.config.getConfig('REGISTRARPAIRS')
        for (parentKey, childKey), pair in sorted(registrarPairs.items()):
            childRow = blockByKey[childKey]
            childCond = condRow(childRow)
            parentRow = blockByKey[parentKey]
            objLayout = layoutForContext(parentRow['_context'])
            for fileDef in pairVlRegistrarMap.values():
                if not isVlSvTop(fileDef, objLayout):
                    continue
                if not artifactPaths.fileMapCondMatch(fileDef, childCond):
                    continue
                for registration in pair['verifRegistrations']:
                    if not registration['pairSpecific']:
                        continue
                    filePath = artifactPaths.expandNewModulePath(
                        fileDef, parentRow['dir'], childRow['block'],
                        registration['physicalFileStub'], objLayout,
                        missingDirOk=True)
                    recordVlTop(fileDef, filePath, registration['topModule'])

    # Per-variant and foreign .sv wrapper tops are enumerated authoritatively by
    # the vlTops pass (the block/registrar record only sees the bare stub, which
    # for a parameterizable block is never emitted). Fold them into the SV set so
    # their generated regions are refreshed like every other generated source.
    for top in vlTops:
        svGenFiles.add(top['physicalSv'])

    # The SV a verilate run reads, as distinct from the modules named on its
    # command line. Project-wide: every top is verilated against the same rtl.f
    # and module set, and A2C_VL_SV_<top> names the one file that differs.
    # Ownership-inclusive, so a reused child's package is an input here even
    # though this project never regenerates it.
    svDepFiles = set(svModuleFiles) | svWrapBodies | {t['physicalSv'] for t in vlTops}
    if rtlDotFPath:
        svDepFiles.add(rtlDotFPath)
    if topContext is not None and 'package_sv' in includeFiles:
        for context in prj.yamlContext[topContext]:
            if context in includeFiles['package_sv']:
                svDepFiles.add(includeFiles['package_sv'][context]['fileName'])

    projectYaml = os.path.join(g.yamlBasePath, os.path.basename(prj.projFile))
    yamlFiles = sorted({os.path.abspath(f) for f in prj.includeValid} | {projectYaml})

    manifest = {
        'mode':          rootLayout['mode'],
        'yamlFiles':     yamlFiles,
        'scSrcDirs':     sorted(dirs.get('sc', set())),
        'svSrcDirs':     sorted(dirs.get('sv', set())),
        'vlWrapDirs':    sorted(dirs.get('vl', set())),
        'cppModuleFiles':sorted(moduleFiles),
        'svFiles':       sorted(svModuleFiles),
        'svDepFiles':    sorted(svDepFiles),
        'scGenFiles':    sorted(scGenFiles),
        'svGenFiles':    sorted(svGenFiles),
        'rtlDotF':       rtlDotFPath,
        'vlTops':        sorted(vlTops, key=lambda t: t['qualifiedTop']),
        'dutTops':       dutTops,
    }
    prj.config.setConfig('BUILDMANIFEST', manifest)

    rootDir = prj.config.getConfig('DIRS')['root']
    _writeBuildManifestMk(rootDir, manifest)
