import os

import pysrc.arch2codeGlobals as g
import pysrc.processYaml as processYaml

# Generated-source toolchain split, mirroring the make find globs: the C++ build
# consumes .cpp/.h/.cppm, the SystemVerilog/verilator build consumes .sv/.svh.
# rtl.f (ext 'f') is a file list, not a compiled source, so it is in neither set.
_CPP_GEN_EXTS = {'cpp', 'h', 'cppm'}
_SV_GEN_EXTS = {'sv', 'svh'}


def _writeBuildManifestMk(rootDir, manifest):
    genDir = os.path.join(rootDir, '.gen')
    os.makedirs(genDir, exist_ok=True)

    def asList(paths):
        return ' '.join(paths)

    lines = [
        "# Generated by arch2code projectCreate (buildManifest). Do not edit.",
        "# Derived build directory/file set for this project's layout; see",
        "# plan-decomp-functional-layout.md (Q-L2 / L2a).",
        f"A2C_MANIFEST_LAYOUT := {manifest['mode']}",
        f"A2C_YAML_FILES := {asList(manifest['yamlFiles'])}",
        f"A2C_SC_SRC_DIRS := {asList(manifest['scSrcDirs'])}",
        f"A2C_SV_SRC_DIRS := {asList(manifest['svSrcDirs'])}",
        f"A2C_VL_WRAP_DIRS := {asList(manifest['vlWrapDirs'])}",
        f"A2C_CPP_MODULE_FILES := {asList(manifest['cppModuleFiles'])}",
        f"A2C_SV_FILES := {asList(manifest['svFiles'])}",
        f"A2C_SC_GEN_FILES := {asList(manifest['scGenFiles'])}",
        f"A2C_SV_GEN_FILES := {asList(manifest['svGenFiles'])}",
        f"A2C_RTL_DOT_F := {manifest['rtlDotF']}",
        f"A2C_VL_TOPS := {asList([t['qualifiedTop'] for t in manifest['vlTops']])}",
    ]
    # DUT-top wrapper per HDL top block, keyed by block name: the wrapper of that
    # block's top instance at its resolved variant. The lint makefile looks this
    # up by HDL_TOP_MODULE (A2C_VL_TOP_<block>) to name exactly one --top-module,
    # unambiguous under multiple variants, prefix-sharing siblings, or several
    # Verilated top-level children.
    for block in sorted(manifest['dutTops']):
        lines.append(f"A2C_VL_TOP_{block} := {manifest['dutTops'][block]}")
    # Per-top verilated-wrapper records: the physical .sv wrapper keyed by the
    # unique design-unit name, so a2c-vl-wrap.mk consumes the DB-derived wrapper
    # path directly instead of deriving tops from filenames. The verilator object
    # name, generated header, include search path, and build-output directory are
    # tool/layout conventions reconstructed in the make infrastructure, not
    # manifest facts.
    for top in manifest['vlTops']:
        name = top['qualifiedTop']
        lines.append(f"A2C_VL_SV_{name} := {top['physicalSv']}")
    lines.append("")
    with open(os.path.join(genDir, 'build.mk'), 'w') as f:
        f.write('\n'.join(lines))


def create(prj):
    # Derive the per-project build directory/file set from the same emission
    # decisions the file generator makes. The manifest uses the persisted layout
    # so artifact placement and build grouping share one project-create contract.
    fileMap = prj.proj['fileGeneration']['fileMap']
    # Per-owning-project layouts. Object placement is resolved under the layout
    # of the project that owns the object's defining context, so a child-owned
    # artifact lands in the child project's segments. The root layout supplies
    # the build-group buckets and the project-scoped verilator wrapper segment.
    projectLayout = prj.config.getConfig('PROJECTLAYOUT')
    rootProject = prj.config.getConfig('PROJECTNAME')
    rootLayout = projectLayout[rootProject]

    dirs = {group: set() for group in rootLayout['buildGroups']}
    moduleFiles = set()
    svModuleFiles = set()
    # Complete generated-file enumeration split by toolchain. Every file the
    # generator emits is recorded here so the makefiles consume the DB-derived
    # set instead of rediscovering GENERATED-marked files on disk.
    scGenFiles = set()
    svGenFiles = set()

    blocksParams = {row['blockKey'] for row in prj.flatData['blocksparams'].values()}
    blockByKey = {row['blockKey']: row for row in prj.flatData['blocks'].values()}

    def layoutForContext(context):
        return projectLayout[prj.contextOwningProject[context]]

    def condRow(blockRow):
        # hasOwnParams is the block's own params: relationship, the one cond
        # field not stored on the block row.
        condData = dict(blockRow)
        condData['hasOwnParams'] = int(blockRow['blockKey'] in blocksParams)
        return condData

    def record(fileDef, filePath, objLayout, rootOwnedGen):
        role = objLayout['segments'][fileDef['basePath']]['buildGroup']
        if role is None:
            return
        dirs[role].add(os.path.dirname(filePath))
        # Gen targets are owned-only: only artifacts whose generation this
        # build-root project owns are enumerated for (re)generation, so a build
        # never spawns no-op arch2code --file invocations against a foreign
        # sub-project's sources. The module/compile sets below (moduleFiles,
        # svModuleFiles) and dirs stay foreign-inclusive so foreign artifacts
        # still COMPILE without being regenerated here.
        if rootOwnedGen:
            for extVal in fileDef['ext'].values():
                genFile = filePath + '.' + extVal
                if extVal in _CPP_GEN_EXTS:
                    scGenFiles.add(genFile)
                elif extVal in _SV_GEN_EXTS:
                    svGenFiles.add(genFile)
        if 'cppm' in fileDef['ext']:
            moduleFiles.add(filePath + '.' + fileDef['ext']['cppm'])
        # Explicit managed SV module files. role=='sv' selects rtlModule and
        # excludes the vl_wrap wrappers (buildGroup vl); packages (context mode)
        # are listed separately by the rtl.f template, not here.
        if 'sv' in fileDef['ext'] and role == 'sv':
            svModuleFiles.add(filePath + '.' + fileDef['ext']['sv'])

    # block mode: one artifact per block per matching block-mode entry.
    for blockRow in blockByKey.values():
        condData = condRow(blockRow)
        objLayout = layoutForContext(blockRow['_context'])
        rootOwnedGen = prj.contextOwningProject[blockRow['_context']] == rootProject
        for fileDef in fileMap.values():
            if fileDef.get('mode', 'block') != 'block':
                continue
            if not processYaml.fileMapCondMatch(fileDef, condData):
                continue
            filePath = processYaml.expandNewModulePath(fileDef, blockRow['dir'],
                                                       blockRow['block'], blockRow['block'],
                                                       objLayout, missingDirOk=True)
            record(fileDef, filePath, objLayout, rootOwnedGen)

    # registrar mode: one trampoline per assembler per distinct matching child it
    # instantiates, under the assembler's directory.
    registrarMap = {k: v for k, v in fileMap.items()
                    if v.get('mode', 'block') == 'registrar'}
    if registrarMap:
        assemblerChildren = dict()
        for inst in prj.flatData['instances'].values():
            containerKey = inst['containerKey']
            if containerKey not in blockByKey:
                continue
            assemblerChildren.setdefault(containerKey, set()).add(inst['instanceTypeKey'])
        # Owner-qualified foreign-Config headers, keyed (owningProject, child) ->
        # module file stub. Computed once in projectCreate.calcForeignConfigHeaders
        # under the same emit gate the config emitter uses, so the manifest never
        # records a header the emitter would not produce. Dedup below because a
        # project with two assembler blocks of one child hits the same pair twice.
        foreignConfigHeaders = prj.config.getConfig('FOREIGNCONFIGHEADERS')
        emittedForeign = set()
        for assemblerKey, childKeys in sorted(assemblerChildren.items()):
            assemblerDir = blockByKey[assemblerKey]['dir']
            # The trampoline is parent-owned: it lands under the assembler's
            # directory, so it resolves under the assembler project layout.
            objLayout = layoutForContext(blockByKey[assemblerKey]['_context'])
            assemblerOwner = prj.contextOwningProject[blockByKey[assemblerKey]['_context']]
            for childKey in sorted(childKeys):
                childRow = blockByKey[childKey]
                childCond = condRow(childRow)
                for fileDef in registrarMap.values():
                    if not processYaml.fileMapCondMatch(fileDef, childCond):
                        continue
                    fileStub = childRow['block']
                    if fileDef.get('foreignConfig', False):
                        if (assemblerOwner, childKey) not in foreignConfigHeaders:
                            continue
                        if (assemblerOwner, childKey) in emittedForeign:
                            continue
                        emittedForeign.add((assemblerOwner, childKey))
                        fileStub = foreignConfigHeaders[(assemblerOwner, childKey)]['stub']
                    filePath = processYaml.expandNewModulePath(fileDef, assemblerDir,
                                                               childRow['block'], fileStub,
                                                               objLayout, missingDirOk=True)
                    # Registrar trampolines / foreign-Config headers are generated
                    # by the owning assembler's project (here, the build root), so
                    # they stay in the gen set even though they reference a foreign
                    # child.
                    record(fileDef, filePath, objLayout, True)

    # context mode: reuse the paths saveIncludeFiles already resolved through
    # the path seam, with validity/smartInclude already applied.
    includeFiles = prj.config.getConfig('INCLUDEFILES')
    for fileType, fileDef in fileMap.items():
        if fileDef.get('mode', 'block') != 'context':
            continue
        for ext in fileDef['ext']:
            expandedType = f"{fileType}_{ext}"
            if expandedType not in includeFiles:
                continue
            # Each include entry is keyed by its context file; resolve its build
            # role under the owning project's layout (path already resolved
            # through that layout in saveIncludeFiles).
            for context, entry in includeFiles[expandedType].items():
                role = layoutForContext(context)['segments'][fileDef['basePath']]['buildGroup']
                if role is None:
                    continue
                dirs[role].add(os.path.dirname(entry['fileName']))
                extVal = fileDef['ext'][ext]
                # Owned-only gen: refresh a context's generated source only when
                # this build-root project owns the context. Foreign contexts still
                # land in moduleFiles/dirs so they COMPILE but are never
                # regenerated by this project's gen.
                if prj.contextOwningProject[context] == rootProject:
                    if extVal in _CPP_GEN_EXTS:
                        scGenFiles.add(entry['fileName'])
                    elif extVal in _SV_GEN_EXTS:
                        svGenFiles.add(entry['fileName'])
                if ext == 'cppm':
                    moduleFiles.add(entry['fileName'])

    # project mode: exactly one artifact per project at its basePath segment
    # root, keyed to the top context (mirrors the newModule project scaffold).
    # A definitions-only project (no top context) emits none; the ownership gate
    # keeps a composed build from recording a referenced child project's copy.
    # Layout-correct path of the per-project rtl.f verilator file list. Published
    # so the shared VL/lint makefiles consume it instead of assuming the
    # functional $root/rtl/rtl.f, which is wrong for a hierarchical multi-node
    # top whose rtl segment lives under <topNode>/rtl. Empty for a definitions-
    # only project (no top context, emits no rtl.f).
    rtlDotFPath = ''
    topContext = prj.config.getConfig('TOPCONTEXT')
    if topContext is not None and prj.contextOwningProject[topContext] == prj.config.getConfig('PROJECTNAME'):
        objLayout = layoutForContext(topContext)
        # In hierarchical layout the per-project artifact anchors to the top
        # context's node directory (the top block's persisted node dir) so its
        # node-relative segment resolves inside the project tree, matching where
        # the newModule scaffold writes it. Functional layout uses $root-
        # absolute segments and needs no node anchor.
        if objLayout['mode'] == 'hierarchical':
            topBlockKey = next(inst['instanceTypeKey']
                               for inst in prj.flatData['instances'].values()
                               if inst['container'] == '_topInstance')
            nodeDir = blockByKey[topBlockKey]['dir']
        else:
            nodeDir = ''
        for fileType, fileDef in fileMap.items():
            if fileDef.get('mode', 'block') != 'project':
                continue
            filePath = processYaml.expandNewModulePath(fileDef, nodeDir, '', '', objLayout, missingDirOk=True)
            # Project-mode artifacts are reached only when the root owns the top
            # context (gated above), so they are always root-owned gen targets.
            record(fileDef, filePath, objLayout, True)
            # The rtl.f file list is resolved through the same emit seam as every
            # other project-mode artifact, so its path is layout-correct in both
            # functional ($root/rtl/rtl.f) and hierarchical (<topNode>/rtl/rtl.f).
            if fileType == 'rtlDotF':
                rtlDotFPath = filePath + '.' + fileDef['ext']['f']

    # Per-top verilated-wrapper records: the explicit (physical .sv -> design
    # unit) set the verilator wrap build consumes, so a2c-vl-wrap.mk names each
    # --top and its physical wrapper directly rather than deriving them from
    # filenames or globbing. The set mirrors the emitted vl-role .sv wrappers:
    # block-mode vlSvWrap (one per variant for a parameterizable block, one bare
    # otherwise; the .svh body is never a top) and registrar-mode vlSvWrapForeign
    # (one owner-qualified top per foreign variant). The design-unit name is the
    # file basename (moduleFileStub + fileMap 'name') -- the same composition the
    # SV wrapper view emits -- so the record and the emitted module name agree.
    vlTops = list()

    def recordVlTop(fileDef, filePath):
        vlTops.append({
            'physicalSv':   filePath + '.' + fileDef['ext']['sv'],
            'qualifiedTop': os.path.basename(filePath),
        })

    def isVlSvTop(fileDef, objLayout):
        # A verilated top is a vl-buildGroup .sv wrapper. The .svh body
        # (vlSvWrapBody) and the SC wrapper (vlScWrap, .h) are excluded here.
        if 'sv' not in fileDef['ext']:
            return False
        return objLayout['segments'][fileDef['basePath']]['buildGroup'] == 'vl'

    # Same-project variant labels per block. A foreign variant (declaring project
    # != the block's config-context owner) is emitted as a registrar-mode
    # owner-qualified top (vlSvWrapForeign), not a block-mode wrapper, so it is
    # excluded here -- mirroring the config emit gate in calcForeignConfigHeaders.
    blockVariants = dict()
    for contextRows in prj.data['parametersvariantsparams'].values():
        for row in contextRows.values():
            configContext = blockByKey[row['blockKey']]['configContext']
            if configContext and row['projectName'] != prj.contextOwningProject[configContext]:
                continue
            blockVariants.setdefault(row['blockKey'], set()).add(row['variant'])

    # DUT-top candidates: the HDL top the lint/vl build drives is named by
    # HDL_TOP_MODULE, which is either the design top block itself (when
    # Verilated) or one of its direct children (a testbench harness wrapping a
    # Verilated DUT). Each candidate maps its block key to that instance's
    # resolved variant, so the wrapper recorded below is the single top for that
    # block -- not every declared variant. The lint makefile then looks up
    # HDL_TOP_MODULE by exact block name (A2C_VL_TOP_<block>) instead of
    # prefix-matching A2C_VL_TOPS, which is ambiguous once the top block declares
    # several variants, a Verilated sibling shares its name prefix, or several
    # direct children are Verilated.
    dutTopVariantByBlock = dict()
    topInst = next((inst for inst in prj.flatData['instances'].values()
                    if inst['container'] == '_topInstance'), None)
    if topInst is not None:
        topBlockKey = topInst['instanceTypeKey']
        dutInsts = list()
        if blockByKey[topBlockKey]['hasVl']:
            dutInsts.append(topInst)
        dutInsts += [inst for inst in prj.flatData['instances'].values()
                     if inst['containerKey'] == topBlockKey
                     and blockByKey[inst['instanceTypeKey']]['hasVl']]
        for inst in dutInsts:
            dutTopVariantByBlock[inst['instanceTypeKey']] = inst['variant'] or ''

    dutTops = dict()
    for blockRow in blockByKey.values():
        condData = condRow(blockRow)
        objLayout = layoutForContext(blockRow['_context'])
        for fileDef in fileMap.values():
            if fileDef.get('mode', 'block') != 'block':
                continue
            if not isVlSvTop(fileDef, objLayout):
                continue
            if not processYaml.fileMapCondMatch(fileDef, condData):
                continue
            block = blockRow['block']
            variants = sorted(blockVariants.get(blockRow['blockKey'], set()))
            variantStubs = [(v, f'{block}_{v}') for v in variants] \
                if (fileDef.get('variant', False) and variants) else [('', block)]
            for variant, stub in variantStubs:
                filePath = processYaml.expandNewModulePath(fileDef, blockRow['dir'],
                                                           block, stub, objLayout,
                                                           missingDirOk=True)
                recordVlTop(fileDef, filePath)
                # Capture a DUT-top wrapper name from the same emission that
                # records it (so the map and A2C_VL_TOPS agree exactly), keyed by
                # block name for the makefile's HDL_TOP_MODULE lookup.
                if dutTopVariantByBlock.get(blockRow['blockKey']) == variant:
                    dutTops[block] = os.path.basename(filePath)

    if registrarMap:
        foreignConfigHeaders = prj.config.getConfig('FOREIGNCONFIGHEADERS')
        emittedForeignTop = set()
        for assemblerKey, childKeys in sorted(assemblerChildren.items()):
            assemblerDir = blockByKey[assemblerKey]['dir']
            objLayout = layoutForContext(blockByKey[assemblerKey]['_context'])
            assemblerOwner = prj.contextOwningProject[blockByKey[assemblerKey]['_context']]
            # A foreign owner-qualified top is a build artifact the reused child's
            # VlRegistrar (in the assembler's owning project) instantiates. A
            # composed build runs ONE vl_wrap build for the whole assembled tree,
            # so it must verilate every foreign top present -- including one owned
            # by a sub-project (its .sv is scaffolded under that sub-project by its
            # own newmodule). The foreignConfigHeaders key uses the assembler's own
            # owner, so the stub/path stay owner-qualified and dedup handles repeats.
            for childKey in sorted(childKeys):
                childRow = blockByKey[childKey]
                childCond = condRow(childRow)
                for fileDef in registrarMap.values():
                    if not fileDef.get('foreignConfig', False):
                        continue
                    if not isVlSvTop(fileDef, objLayout):
                        continue
                    if not processYaml.fileMapCondMatch(fileDef, childCond):
                        continue
                    if (assemblerOwner, childKey) not in foreignConfigHeaders:
                        continue
                    stubBase = foreignConfigHeaders[(assemblerOwner, childKey)]['stub']
                    for variant in foreignConfigHeaders[(assemblerOwner, childKey)]['variants']:
                        dedupKey = (assemblerOwner, childKey, variant)
                        if dedupKey in emittedForeignTop:
                            continue
                        emittedForeignTop.add(dedupKey)
                        filePath = processYaml.expandNewModulePath(
                            fileDef, assemblerDir, childRow['block'],
                            f'{stubBase}_{variant}', objLayout, missingDirOk=True)
                        recordVlTop(fileDef, filePath)

    # Per-variant and foreign .sv wrapper tops are enumerated authoritatively by
    # the vlTops pass (the block/registrar record only sees the bare stub, which
    # for a parameterizable block is never emitted). Fold them into the SV set so
    # their generated regions are refreshed like every other generated source.
    for top in vlTops:
        svGenFiles.add(top['physicalSv'])

    projectYaml = os.path.join(g.yamlBasePath, os.path.basename(prj.projFile))
    yamlFiles = sorted({os.path.abspath(f) for f in prj.includeValid} | {projectYaml})

    manifest = {
        'mode':          rootLayout['mode'],
        'yamlFiles':     yamlFiles,
        'scSrcDirs':     sorted(dirs.get('sc', set())),
        'svSrcDirs':     sorted(dirs.get('sv', set())),
        'vlWrapDirs':    sorted(dirs.get('vl', set())),
        'cppModuleFiles':sorted(moduleFiles),
        'svFiles':       sorted(svModuleFiles),
        'scGenFiles':    sorted(scGenFiles),
        'svGenFiles':    sorted(svGenFiles),
        'rtlDotF':       rtlDotFPath,
        'vlTops':        sorted(vlTops, key=lambda t: t['qualifiedTop']),
        'dutTops':       dutTops,
    }
    prj.config.setConfig('BUILDMANIFEST', manifest)

    rootDir = prj.config.getConfig('DIRS')['root']
    _writeBuildManifestMk(rootDir, manifest)
