import os

import pysrc.arch2codeGlobals as g
import pysrc.processYaml as processYaml


def _writeBuildManifestMk(rootDir, manifest):
    genDir = os.path.join(rootDir, '.gen')
    os.makedirs(genDir, exist_ok=True)

    def asList(paths):
        return ' '.join(paths)

    lines = [
        "# Generated by arch2code projectCreate (buildManifest). Do not edit.",
        "# Derived build directory/file set for this project's layout; see",
        "# plan-decomp-functional-layout.md (Q-L2 / L2a).",
        f"A2C_MANIFEST_LAYOUT := {manifest['mode']}",
        f"A2C_PRJ_YAML := {manifest['projectYaml']}",
        f"A2C_YAML_FILES := {asList(manifest['yamlFiles'])}",
        f"A2C_SC_SRC_DIRS := {asList(manifest['scSrcDirs'])}",
        f"A2C_SV_SRC_DIRS := {asList(manifest['svSrcDirs'])}",
        f"A2C_VL_WRAP_DIRS := {asList(manifest['vlWrapDirs'])}",
        f"A2C_CPP_MODULE_FILES := {asList(manifest['cppModuleFiles'])}",
        f"A2C_SV_FILES := {asList(manifest['svFiles'])}",
        f"A2C_VL_BUILD_DIR := {manifest['vlBuildDir']}",
        f"A2C_VL_TOPS := {asList([t['qualifiedTop'] for t in manifest['vlTops']])}",
    ]
    # Per-top verilated-wrapper records: physical .sv, design-unit (--top), the
    # include search path, the generated V header, and the archived object. Keyed
    # by the unique design-unit name so a2c-vl-wrap.mk consumes each fact directly
    # instead of deriving tops from filenames or globbing objects.
    for top in manifest['vlTops']:
        name = top['qualifiedTop']
        lines.append(f"A2C_VL_SV_{name} := {top['physicalSv']}")
        lines.append(f"A2C_VL_INCDIRS_{name} := {asList(top['includeDirs'])}")
        lines.append(f"A2C_VL_VHDR_{name} := {top['generatedVHeader']}")
        lines.append(f"A2C_VL_OBJ_{name} := {top['objectIdentity']}")
    lines.append("")
    with open(os.path.join(genDir, 'build.mk'), 'w') as f:
        f.write('\n'.join(lines))


def _projectScopedSegment(layout, basePathKey):
    segment = layout['segments'][basePathKey]['path']
    if layout['mode'] == 'hierarchical' and not os.path.isabs(segment):
        return os.path.join(layout['prj'], segment)
    return segment


def create(prj):
    # Derive the per-project build directory/file set from the same emission
    # decisions the file generator makes. The manifest uses the persisted layout
    # so artifact placement and build grouping share one project-create contract.
    fileMap = prj.proj['fileGeneration']['fileMap']
    # Per-owning-project layouts. Object placement is resolved under the layout
    # of the project that owns the object's defining context, so a child-owned
    # artifact lands in the child project's segments. The root layout supplies
    # the build-group buckets and the project-scoped verilator wrapper segment.
    projectLayout = prj.config.getConfig('PROJECTLAYOUT')
    rootLayout = projectLayout[prj.config.getConfig('PROJECTNAME')]

    dirs = {group: set() for group in rootLayout['buildGroups']}
    moduleFiles = set()
    svModuleFiles = set()

    blocksParams = {row['blockKey'] for row in prj.flatData['blocksparams'].values()}
    blockByKey = {row['blockKey']: row for row in prj.flatData['blocks'].values()}

    def layoutForContext(context):
        return projectLayout[prj.contextOwningProject[context]]

    def condRow(blockRow):
        # hasOwnParams is the block's own params: relationship, the one cond
        # field not stored on the block row.
        condData = dict(blockRow)
        condData['hasOwnParams'] = int(blockRow['blockKey'] in blocksParams)
        return condData

    def record(fileDef, filePath, objLayout):
        role = objLayout['segments'][fileDef['basePath']]['buildGroup']
        if role is None:
            return
        dirs[role].add(os.path.dirname(filePath))
        if 'cppm' in fileDef['ext']:
            moduleFiles.add(filePath + '.' + fileDef['ext']['cppm'])
        # Explicit managed SV module files. role=='sv' selects rtlModule and
        # excludes the vl_wrap wrappers (buildGroup vl); packages (context mode)
        # are listed separately by the rtl.f template, not here.
        if 'sv' in fileDef['ext'] and role == 'sv':
            svModuleFiles.add(filePath + '.' + fileDef['ext']['sv'])

    # block mode: one artifact per block per matching block-mode entry.
    for blockRow in blockByKey.values():
        condData = condRow(blockRow)
        objLayout = layoutForContext(blockRow['_context'])
        for fileDef in fileMap.values():
            if fileDef.get('mode', 'block') != 'block':
                continue
            if not processYaml.fileMapCondMatch(fileDef, condData):
                continue
            filePath = processYaml.expandNewModulePath(fileDef, blockRow['dir'],
                                                       blockRow['block'], blockRow['block'],
                                                       objLayout, missingDirOk=True)
            record(fileDef, filePath, objLayout)

    # registrar mode: one trampoline per assembler per distinct matching child it
    # instantiates, under the assembler's directory.
    registrarMap = {k: v for k, v in fileMap.items()
                    if v.get('mode', 'block') == 'registrar'}
    if registrarMap:
        assemblerChildren = dict()
        for inst in prj.flatData['instances'].values():
            containerKey = inst['containerKey']
            if containerKey not in blockByKey:
                continue
            assemblerChildren.setdefault(containerKey, set()).add(inst['instanceTypeKey'])
        # Owner-qualified foreign-Config headers, keyed (owningProject, child) ->
        # module file stub. Computed once in projectCreate.calcForeignConfigHeaders
        # under the same emit gate the config emitter uses, so the manifest never
        # records a header the emitter would not produce. Dedup below because a
        # project with two assembler blocks of one child hits the same pair twice.
        foreignConfigHeaders = prj.config.getConfig('FOREIGNCONFIGHEADERS')
        emittedForeign = set()
        for assemblerKey, childKeys in sorted(assemblerChildren.items()):
            assemblerDir = blockByKey[assemblerKey]['dir']
            # The trampoline is parent-owned: it lands under the assembler's
            # directory, so it resolves under the assembler project layout.
            objLayout = layoutForContext(blockByKey[assemblerKey]['_context'])
            assemblerOwner = prj.contextOwningProject[blockByKey[assemblerKey]['_context']]
            for childKey in sorted(childKeys):
                childRow = blockByKey[childKey]
                childCond = condRow(childRow)
                for fileDef in registrarMap.values():
                    if not processYaml.fileMapCondMatch(fileDef, childCond):
                        continue
                    fileStub = childRow['block']
                    if fileDef.get('foreignConfig', False):
                        if (assemblerOwner, childKey) not in foreignConfigHeaders:
                            continue
                        if (assemblerOwner, childKey) in emittedForeign:
                            continue
                        emittedForeign.add((assemblerOwner, childKey))
                        fileStub = foreignConfigHeaders[(assemblerOwner, childKey)]['stub']
                    filePath = processYaml.expandNewModulePath(fileDef, assemblerDir,
                                                               childRow['block'], fileStub,
                                                               objLayout, missingDirOk=True)
                    record(fileDef, filePath, objLayout)

    # context mode: reuse the paths saveIncludeFiles already resolved through
    # the path seam, with validity/smartInclude already applied.
    includeFiles = prj.config.getConfig('INCLUDEFILES')
    for fileType, fileDef in fileMap.items():
        if fileDef.get('mode', 'block') != 'context':
            continue
        for ext in fileDef['ext']:
            expandedType = f"{fileType}_{ext}"
            if expandedType not in includeFiles:
                continue
            # Each include entry is keyed by its context file; resolve its build
            # role under the owning project's layout (path already resolved
            # through that layout in saveIncludeFiles).
            for context, entry in includeFiles[expandedType].items():
                role = layoutForContext(context)['segments'][fileDef['basePath']]['buildGroup']
                if role is None:
                    continue
                dirs[role].add(os.path.dirname(entry['fileName']))
                if ext == 'cppm':
                    moduleFiles.add(entry['fileName'])

    # project mode: exactly one artifact per project at its basePath segment
    # root, keyed to the top context (mirrors the newModule project scaffold).
    # A definitions-only project (no top context) emits none; the ownership gate
    # keeps a composed build from recording a referenced child project's copy.
    topContext = prj.config.getConfig('TOPCONTEXT')
    if topContext is not None and prj.contextOwningProject[topContext] == prj.config.getConfig('PROJECTNAME'):
        objLayout = layoutForContext(topContext)
        # In hierarchical layout the per-project artifact anchors to the top
        # context's node directory (the top block's persisted node dir) so its
        # node-relative segment resolves inside the project tree, matching where
        # the newModule scaffold writes it. Functional layout uses $root-
        # absolute segments and needs no node anchor.
        if objLayout['mode'] == 'hierarchical':
            topBlockKey = next(inst['instanceTypeKey']
                               for inst in prj.flatData['instances'].values()
                               if inst['container'] == '_topInstance')
            nodeDir = blockByKey[topBlockKey]['dir']
        else:
            nodeDir = ''
        for fileDef in fileMap.values():
            if fileDef.get('mode', 'block') != 'project':
                continue
            filePath = processYaml.expandNewModulePath(fileDef, nodeDir, '', '', objLayout, missingDirOk=True)
            record(fileDef, filePath, objLayout)

    # The verilator wrapper segment root (holds sc_main and the verilated build
    # dir): a known location, not a discovered one. The retired vl_wrap.cpp
    # aggregator no longer lives here; `_verif` registration moved to the
    # per-assembler VlRegistrar.cpp files discovered under scSrcDirs.
    vlSegment = _projectScopedSegment(rootLayout, 'vl_wrap')
    if dirs['vl']:
        dirs['vl'].add(vlSegment)

    # Per-top verilated-wrapper records: the explicit (physical .sv -> design
    # unit) set the verilator wrap build consumes, so a2c-vl-wrap.mk names each
    # --top and its archived object directly rather than deriving them from
    # filenames or globbing. The set mirrors the emitted vl-role .sv wrappers:
    # block-mode vlSvWrap (one per variant for a parameterizable block, one bare
    # otherwise; the .svh body is never a top) and registrar-mode vlSvWrapForeign
    # (one owner-qualified top per foreign variant). The design-unit name is the
    # file basename (moduleFileStub + fileMap 'name') -- the same composition the
    # SV wrapper view emits -- so the record and the emitted module name agree,
    # and the verilated object/header follow verilator's V<top>__ALL.o / V<top>.h.
    vlIncludeDirs = sorted(dirs['vl'])
    vlTops = list()

    def recordVlTop(fileDef, filePath):
        qualifiedTop = os.path.basename(filePath)
        vlTops.append({
            'physicalSv':       filePath + '.' + fileDef['ext']['sv'],
            'qualifiedTop':     qualifiedTop,
            'includeDirs':      vlIncludeDirs,
            'generatedVHeader': 'V' + qualifiedTop + '.h',
            'objectIdentity':   'V' + qualifiedTop + '__ALL.o',
        })

    def isVlSvTop(fileDef, objLayout):
        # A verilated top is a vl-buildGroup .sv wrapper. The .svh body
        # (vlSvWrapBody) and the SC wrapper (vlScWrap, .h) are excluded here.
        if 'sv' not in fileDef['ext']:
            return False
        return objLayout['segments'][fileDef['basePath']]['buildGroup'] == 'vl'

    # Same-project variant labels per block. A foreign variant (declaring project
    # != the block's config-context owner) is emitted as a registrar-mode
    # owner-qualified top (vlSvWrapForeign), not a block-mode wrapper, so it is
    # excluded here -- mirroring the config emit gate in calcForeignConfigHeaders.
    blockVariants = dict()
    for contextRows in prj.data['parametersvariants'].values():
        for row in contextRows.values():
            configContext = blockByKey[row['blockKey']]['configContext']
            if configContext and row['projectName'] != prj.contextOwningProject[configContext]:
                continue
            blockVariants.setdefault(row['blockKey'], set()).add(row['variant'])

    for blockRow in blockByKey.values():
        condData = condRow(blockRow)
        objLayout = layoutForContext(blockRow['_context'])
        for fileDef in fileMap.values():
            if fileDef.get('mode', 'block') != 'block':
                continue
            if not isVlSvTop(fileDef, objLayout):
                continue
            if not processYaml.fileMapCondMatch(fileDef, condData):
                continue
            block = blockRow['block']
            variants = sorted(blockVariants.get(blockRow['blockKey'], set()))
            stubs = [f'{block}_{v}' for v in variants] \
                if (fileDef.get('variant', False) and variants) else [block]
            for stub in stubs:
                filePath = processYaml.expandNewModulePath(fileDef, blockRow['dir'],
                                                           block, stub, objLayout,
                                                           missingDirOk=True)
                recordVlTop(fileDef, filePath)

    if registrarMap:
        foreignConfigHeaders = prj.config.getConfig('FOREIGNCONFIGHEADERS')
        emittedForeignTop = set()
        for assemblerKey, childKeys in sorted(assemblerChildren.items()):
            assemblerDir = blockByKey[assemblerKey]['dir']
            objLayout = layoutForContext(blockByKey[assemblerKey]['_context'])
            assemblerOwner = prj.contextOwningProject[blockByKey[assemblerKey]['_context']]
            # A foreign owner-qualified top is a build artifact the reused child's
            # VlRegistrar (in the assembler's owning project) instantiates. A
            # composed build runs ONE vl_wrap build for the whole assembled tree,
            # so it must verilate every foreign top present -- including one owned
            # by a sub-project (its .sv is scaffolded under that sub-project by its
            # own newmodule). The foreignConfigHeaders key uses the assembler's own
            # owner, so the stub/path stay owner-qualified and dedup handles repeats.
            for childKey in sorted(childKeys):
                childRow = blockByKey[childKey]
                childCond = condRow(childRow)
                for fileDef in registrarMap.values():
                    if not fileDef.get('foreignConfig', False):
                        continue
                    if not isVlSvTop(fileDef, objLayout):
                        continue
                    if not processYaml.fileMapCondMatch(fileDef, childCond):
                        continue
                    if (assemblerOwner, childKey) not in foreignConfigHeaders:
                        continue
                    stubBase = foreignConfigHeaders[(assemblerOwner, childKey)]['stub']
                    for variant in foreignConfigHeaders[(assemblerOwner, childKey)]['variants']:
                        dedupKey = (assemblerOwner, childKey, variant)
                        if dedupKey in emittedForeignTop:
                            continue
                        emittedForeignTop.add(dedupKey)
                        filePath = processYaml.expandNewModulePath(
                            fileDef, assemblerDir, childRow['block'],
                            f'{stubBase}_{variant}', objLayout, missingDirOk=True)
                        recordVlTop(fileDef, filePath)

    projectYaml = os.path.join(g.yamlBasePath, os.path.basename(prj.projFile))
    yamlFiles = sorted({os.path.abspath(f) for f in prj.includeValid} | {projectYaml})

    manifest = {
        'mode':          rootLayout['mode'],
        'projectYaml':   projectYaml,
        'yamlFiles':     yamlFiles,
        'scSrcDirs':     sorted(dirs.get('sc', set())),
        'svSrcDirs':     sorted(dirs.get('sv', set())),
        'vlWrapDirs':    sorted(dirs.get('vl', set())),
        'cppModuleFiles':sorted(moduleFiles),
        'svFiles':       sorted(svModuleFiles),
        'vlBuildDir':    vlSegment,
        'vlTops':        sorted(vlTops, key=lambda t: t['qualifiedTop']),
    }
    prj.config.setConfig('BUILDMANIFEST', manifest)

    rootDir = prj.config.getConfig('DIRS')['root']
    _writeBuildManifestMk(rootDir, manifest)
