# Example project file that defines project level information


projectName: mixed

# project files can be regular input files, regular input files with additional projectFiles sections, or additional ProjectFiles.
# note in the case of additional project files any top level controls (such as schema:) are ignored
# relative path names are resolved based on location of project file (this includes sub projects)
projectFiles:
  - mixed.yaml
  - mixedBlockC.yaml


addressControl: exampleAddress.yaml

topInstance: mixed_tb

dirs: # this is list of locations that can be referenced as base path in fileMap section
  root: ../..    # project root directory relative to project file - required
  base: $root/base
  model: $root/model
  rtl: $root/rtl
  vl_wrap: $root/verif/vl_wrap
  tb: $root/tb
  fwInc: $root/fw/include

# information about project directory structure to enable simplified maintenance
# and generation of file for new blocks. Note that directory structure will mirror
# architecture hierarchy.
fileGeneration:
  template: $a2c/templates/fileGen/fileGen.py
#  fileMap:
    # filePrefix and fileSuffix will be added to the module name to generate a filename
    # path to the file will be based on command line input and the base path defined in the dirs section
    # note that basePath should reference a path key in the dirs section
#    includeFW   : { name : "IncludesFW",      ext: {hdr: "h", src: "cpp"}, cond: {smartInclude: true},          mode: context, basePath: fwInc,   desc: "yaml based fw include file"}


  # standard copyright statement to be added to all generated files - change to suite your company
  fileCopyrightStatement: "copyright the arch2code project contributors, see https://bitbucket.org/arch2code/arch2code/src/main/LICENSE"
  regBlockNaming: {instancePrefix: 'u', blockSuffix: 'Regs', camelCase: true} # naming convention for register handler blocks - instancePrefix is prefix for instance names, blockSuffix is suffix for block names
postProcess:
  - $a2c/config/postParseRegister.py
  - $a2c/config/postParseChecks.py