
#ifndef XPCPLAYOUTTOPVARIANTCONFIG_H_
#define XPCPLAYOUTTOPVARIANTCONFIG_H_
// 

// GENERATED_CODE_PARAM --project=xpCpLayout --context=../../yaml/xpCpLayoutTop.yaml
// GENERATED_CODE_BEGIN --template=config

// GENERATED_CODE_END

#endif //XPCPLAYOUTTOPVARIANTCONFIG_H_
