#!/usr/bin/env python3
"""
Table Format Package

A flexible Python library for formatting various data structures in text-based tabular format.
Uses only Python standard library - no external dependencies.

Generated by AI: GitHub Copilot
Date: November 5, 2025
Purpose: Python package for generic text-based tabular formatting

Public API:
    TableFormatter - Main class for table formatting functionality
    format_dict_table - Convenience function for dictionary tables
    format_list_table - Convenience function for list tables
    format_json_file - Convenience function for JSON file tables
"""

from .core import TableFormatter
from .utils import format_dict_table, format_list_table, format_json_file

# Package metadata
__version__ = "1.0.0"
__author__ = "GitHub Copilot (AI Generated)"
__email__ = "N/A"
__description__ = "Generic library for text-based tabular formatting of data structures"

# Public API exports
__all__ = [
    'TableFormatter',
    'format_dict_table',
    'format_list_table',
    'format_json_file',
    '__version__'
]