#!/usr/bin/env python3
"""
Examples and demonstrations for the table_format package.

Generated by AI: GitHub Copilot
Date: November 5, 2025
Purpose: Example usage and demonstrations of table formatting functionality
"""

import sys
import os

# Add parent directory to path to find table_format package
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from table_format import TableFormatter
from table_format import format_dict_table, format_list_table


def demo_simple_dictionary():
    """Demonstrate simple dictionary formatting."""
    print("=== Simple Dictionary Example ===")
    config_data = {
        'debug_mode': 'True',
        'max_connections': '100',
        'timeout': '30',
        'log_level': 'INFO',
        'database_url': 'postgresql://localhost:5432/mydb'
    }

    format_dict_table(
        config_data,
        [('Key', 25), ('Value', 40)],
        title="Application Configuration"
    )


def demo_server_metrics():
    """Demonstrate server performance metrics formatting."""
    print("\n=== Server Performance Metrics ===")
    server_stats = {
        'web-01': {'cpu': 45.2, 'memory': 78.5, 'disk': 23.1, 'status': 'active'},
        'web-02': {'cpu': 32.8, 'memory': 65.3, 'disk': 45.7, 'status': 'active'},
        'db-01': {'cpu': 67.9, 'memory': 89.2, 'disk': 78.3, 'status': 'warning'},
        'cache-01': {'cpu': 12.3, 'memory': 34.5, 'disk': 12.8, 'status': 'active'}
    }

    def server_extractor(key, value, columns):
        return [
            key,
            f"{value.get('cpu', 0):.1f}%",
            f"{value.get('memory', 0):.1f}%",
            f"{value.get('disk', 0):.1f}%",
            value.get('status', '')
        ]

    format_dict_table(
        server_stats,
        [('Server', 15), ('CPU', 8), ('Memory', 8), ('Disk', 8), ('Status', 10)],
        extractor=server_extractor,
        title="Server Monitoring Dashboard"
    )


def demo_transactions():
    """Demonstrate transaction list formatting."""
    print("\n=== Financial Transaction Log ===")
    transactions = [
        {'id': 'TXN001', 'amount': 150.75, 'type': 'credit', 'account': 'ACC123'},
        {'id': 'TXN002', 'amount': 45.20, 'type': 'debit', 'account': 'ACC456'},
        {'id': 'TXN003', 'amount': 200.00, 'type': 'credit', 'account': 'ACC123'},
        {'id': 'TXN004', 'amount': 78.90, 'type': 'debit', 'account': 'ACC789'}
    ]

    def transaction_extractor(index, item, columns):
        return [
            item.get('id', ''),
            f"${item.get('amount', 0):.2f}",
            item.get('type', ''),
            item.get('account', '')
        ]

    format_list_table(
        transactions,
        [('ID', 8), ('Amount', 12), ('Type', 8), ('Account', 10)],
        extractor=transaction_extractor,
        title="Recent Transactions"
    )


def demo_border_styles():
    """Demonstrate different border styles."""
    print("\n=== Border Style Variations ===")
    simple_data = {
        'style1': 'Standard ASCII borders',
        'style2': 'Minimal spacing'
    }

    table = TableFormatter('ascii')
    print("\nASCII Style:")
    print(table.format_dict_table(simple_data, [('Key', 15), ('Value', 30)]), end='')

    table = TableFormatter('minimal')
    print("\nMinimal Style:")
    print(table.format_dict_table(simple_data, [('Key', 15), ('Value', 30)]), end='')


def demo_truncation_modes():
    """Demonstrate different truncation modes with long text."""
    print("\n=== Truncation Mode Demonstration ===")

    long_text_data = {
        'file1': 'very_long_filename_that_exceeds_column_width.txt',
        'file2': '/path/to/very/long/directory/structure/file.log',
        'url': 'https://example.com/api/v1/users/12345/profile/settings',
        'description': 'This is a very long description that will definitely exceed the column width'
    }

    # Narrow columns to force truncation
    columns = [('Key', 12), ('Value', 25)]

    # Right-aligned truncation (default) - shows end of text
    print("\nRight-aligned truncation (shows end of text):")
    table_right = TableFormatter('ascii', 'right')
    print(table_right.format_dict_table(long_text_data, columns, title="Right Truncation Demo"), end='')

    # Left-aligned truncation - shows start of text
    print("\nLeft-aligned truncation (shows start of text):")
    table_left = TableFormatter('ascii', 'left')
    print(table_left.format_dict_table(long_text_data, columns, title="Left Truncation Demo"), end='')

    # Example use cases explanation
    print("\n" + "=" * 60)
    print("TRUNCATION MODE USE CASES")
    print("=" * 60)
    print("✓ Right truncation: Best for filenames, URLs, IDs")
    print("  - Shows important endings: '...filename.txt'")
    print("  - Preserves file extensions and ID suffixes")
    print()
    print("✓ Left truncation: Best for descriptions, titles")
    print("  - Shows important beginnings: 'Important title...'")
    print("  - Preserves context and main subject")


def demo_convenience_functions():
    """Demonstrate convenience functions with truncation modes."""
    print("\n=== Convenience Functions with Truncation ===")

    sample_data = [
        {'name': 'very_long_component_name_that_exceeds_width', 'type': 'module', 'size': '1024'},
        {'name': 'short_name', 'type': 'interface', 'size': '256'},
        {'name': 'another_extremely_long_component_name_here', 'type': 'class', 'size': '512'}
    ]

    columns = [('Name', 20), ('Type', 10), ('Size', 8)]

    print("\nUsing convenience function with right truncation:")
    format_list_table(sample_data, columns, title="Right Truncation", truncation_mode='right')

    print("\nUsing convenience function with left truncation:")
    format_list_table(sample_data, columns, title="Left Truncation", truncation_mode='left')

def demo_autosize_feature():
    """Demonstrate the autosize feature with width=0."""
    print("\n=== Autosize Feature Demonstration ===")

    # Example 1: Basic autosize - all columns size automatically
    print("\n--- Example 1: All Columns Autosize ---")
    component_data = {
        'cpu': {'type': 'Processor', 'model': 'Intel Core i7-12700K', 'specs': '12 cores, 3.6 GHz base'},
        'gpu': {'type': 'Graphics Card', 'model': 'NVIDIA GeForce RTX 4080', 'specs': '16GB GDDR6X, 2505 MHz boost'},
        'ram': {'type': 'Memory', 'model': 'Corsair Vengeance LPX', 'specs': '32GB DDR4-3200 CL16'},
        'ssd': {'type': 'Storage', 'model': 'Samsung 980 PRO', 'specs': '2TB NVMe PCIe 4.0, 7000 MB/s read'}
    }

    # All columns autosize (width=0)
    autosize_columns = [('Component', 0), ('Type', 0), ('Model', 0), ('Specifications', 0)]

    def component_extractor(key, value, columns):
        return [key, value['type'], value['model'], value['specs']]

    format_dict_table(
        component_data,
        autosize_columns,
        extractor=component_extractor,
        title="PC Components (All Columns Autosize)"
    )

    # Example 2: Mixed sizing - some fixed, some autosize
    print("\n--- Example 2: Mixed Column Sizing ---")
    mixed_columns = [('Component', 10), ('Type', 0), ('Model', 0), ('Specifications', 50)]

    format_dict_table(
        component_data,
        mixed_columns,
        extractor=component_extractor,
        title="PC Components (Mixed Sizing: Fixed/Auto/Auto/Fixed)"
    )

    # Example 3: Dynamic content with varying lengths
    print("\n--- Example 3: Dynamic Content Lengths ---")
    project_data = [
        {'name': 'AI', 'description': 'Machine learning project', 'team': 'Data Science', 'status': 'Active'},
        {'name': 'WebApp', 'description': 'Full-stack web application with React frontend and Node.js backend', 'team': 'Frontend', 'status': 'In Progress'},
        {'name': 'DatabaseOptimization', 'description': 'Performance tuning and query optimization for PostgreSQL database serving millions of requests daily', 'team': 'Backend Infrastructure', 'status': 'Completed'},
        {'name': 'API', 'description': 'REST API', 'team': 'Backend', 'status': 'Planning'}
    ]

    # Autosize all columns to accommodate varying content lengths
    project_columns = [('Project', 0), ('Description', 0), ('Team', 0), ('Status', 0)]

    format_list_table(
        project_data,
        project_columns,
        title="Project Status (All Autosized)"
    )

    # Example 4: Benefits demonstration
    print("\n--- Example 4: Benefits of Autosize ---")
    print("Compare fixed width vs autosize for the same data:")

    sample_data = {
        'short': 'Small value',
        'medium_length_key': 'This is a medium length value',
        'very_long_key_name_here': 'This is a very long value that would normally require careful width planning'
    }

    print("\nFixed width (may truncate or waste space):")
    format_dict_table(sample_data, [('Key', 15), ('Value', 30)], title="Fixed Width Example")

    print("\nAutosize (optimal fit):")
    format_dict_table(sample_data, [('Key', 0), ('Value', 0)], title="Autosize Example")

    print("\n" + "=" * 60)
    print("AUTOSIZE FEATURE BENEFITS")
    print("=" * 60)
    print("✓ No manual width calculation needed")
    print("✓ Automatically accommodates varying content lengths")
    print("✓ Prevents truncation of important data")
    print("✓ Optimizes screen space usage")
    print("✓ Works with any data structure")
    print("✓ Can be mixed with fixed-width columns")
    print("✓ Configurable maximum width limits")

def demo_configurable_autosize_limits():
    """Demonstrate configurable maximum autosize width limits."""
    print("\n=== Configurable Autosize Width Limits ===")

    # Data with extremely long content that would create very wide columns
    long_content_data = {
        'config_file': '/very/long/path/to/configuration/files/application.conf',
        'description': 'This is an extremely long description that would normally create a very wide column but can be controlled with max_autosize_width parameter to prevent tables from becoming too wide for comfortable viewing',
        'status': 'active'
    }

    print("\n--- Example 1: Default Autosize Behavior (max_width=50) ---")
    format_dict_table(
        long_content_data,
        [('Setting', 0), ('Value', 0)],
        title="Default Autosize Limits (50 chars max)"
    )

    print("\n--- Example 2: Conservative Autosize (max_width=25) ---")
    format_dict_table(
        long_content_data,
        [('Setting', 0), ('Value', 0)],
        title="Conservative Autosize (25 chars max)",
        max_autosize_width=25
    )

    print("\n--- Example 3: Generous Autosize (max_width=80) ---")
    format_dict_table(
        long_content_data,
        [('Setting', 0), ('Value', 0)],
        title="Generous Autosize (80 chars max)",
        max_autosize_width=80
    )

    print("\n--- Example 4: Using TableFormatter Class ---")
    from table_format import TableFormatter

    # Create formatter with custom max autosize width
    formatter = TableFormatter('ascii', 'right', max_autosize_width=30)
    result = formatter.format_dict_table(
        long_content_data,
        [('Setting', 0), ('Value', 0)],
        title="Custom TableFormatter (30 chars max)"
    )
    print(result, end='')

    print("\n" + "=" * 60)
    print("CONFIGURABLE AUTOSIZE BENEFITS")
    print("=" * 60)
    print("✓ Prevents extremely wide tables")
    print("✓ Maintains readability on narrow screens")
    print("✓ Balances content visibility with layout")
    print("✓ Uses existing truncation modes for overflow")
    print("✓ Configurable per table or globally")
    print("✓ Reasonable defaults work for most cases")

def demo_main():
    """Main demonstration function."""
    print("=" * 80)
    print("TABLE FORMAT PACKAGE DEMONSTRATION")
    print("=" * 80)

    demo_simple_dictionary()
    demo_server_metrics()
    demo_transactions()
    demo_border_styles()
    demo_truncation_modes()
    demo_convenience_functions()
    demo_autosize_feature()
    demo_configurable_autosize_limits()

    print("\n" + "=" * 80)
    print("PACKAGE FEATURES SUMMARY")
    print("=" * 80)
    print("✓ Dictionary formatting (nested or flat)")
    print("✓ List formatting (dictionaries or arrays)")
    print("✓ JSON file loading and formatting")
    print("✓ Custom data extractors")
    print("✓ Multiple border styles")
    print("✓ Smart truncation modes (right/left)")
    print("✓ Automatic column sizing (width=0)")
    print("✓ Configurable autosize width limits")
    print("✓ Flexible column configuration")
    print("✓ No external dependencies")
    print("✓ Easy to use API")


if __name__ == "__main__":
    demo_main()