#!/usr/bin/env python3
"""
Setup script for the table_display package.

Generated by AI: GitHub Copilot
Date: November 5, 2025
Purpose: Package installation and distribution setup
"""

from setuptools import setup, find_packages
import os

# Read README file for long description
def read_readme():
    readme_path = os.path.join(os.path.dirname(__file__), 'README.md')
    if os.path.exists(readme_path):
        with open(readme_path, 'r', encoding='utf-8') as f:
            return f.read()
    return "Generic library for text-based tabular display of data structures"

# Package version
__version__ = "1.0.0"

setup(
    name="table_display",
    version=__version__,
    author="GitHub Copilot (AI Generated)",
    author_email="N/A",
    description="Generic library for text-based tabular display of data structures",
    long_description=read_readme(),
    long_description_content_type="text/markdown",
    url="https://github.com/user/table_display",  # Update with actual repository URL
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Text Processing :: General",
        "Topic :: Utilities",
    ],
    python_requires=">=3.6",
    install_requires=[
        # No external dependencies - uses only Python standard library
    ],
    extras_require={
        "dev": [
            "pytest>=6.0",
            "pytest-cov>=2.0",
            "black>=21.0",
            "flake8>=3.8",
        ],
    },
    package_data={
        "table_display": ["*.md"],
    },
    include_package_data=True,
    zip_safe=False,
    keywords="table display formatting text console cli",
    project_urls={
        "Bug Reports": "https://github.com/user/table_display/issues",
        "Source": "https://github.com/user/table_display",
        "Documentation": "https://github.com/user/table_display/blob/main/README.md",
    },
    entry_points={
        "console_scripts": [
            "table-display-demo=table_display.examples:demo_main",
        ],
    },
)