#!/usr/bin/env python3
"""
Utility functions for the table_format package.

Generated by AI: GitHub Copilot
Date: November 5, 2025
Purpose: Convenience functions for quick table formatting operations
"""

from typing import Any, Dict, List, Tuple, Union, Callable, Optional
from .core import TableFormatter


def format_dict_table(data: Dict[str, Any],
                      columns: List[Tuple[str, int]],
                      extractor: Optional[Callable] = None,
                      title: str = None,
                      border_style: str = 'ascii',
                      truncation_mode: str = 'right',
                      max_autosize_width: int = 50,
                      print_output: bool = True) -> str:
    """
    Convenience function to quickly format a dictionary as a table.

    Args:
        data (dict): Dictionary data to format
        columns (list): List of tuples (column_name, width) where width=0 means autosize
        extractor (callable, optional): Function to extract row data
        title (str, optional): Table title
        border_style (str): Border style ('ascii', 'minimal')
        truncation_mode (str): Truncation mode ('right', 'left')
            - 'right': Ellipsis at beginning (default): "...end of text"
            - 'left': Ellipsis at end: "start of text..."
        max_autosize_width (int): Maximum width for autosize columns (default: 50)
        print_output (bool): Whether to print the table (default: True)

    Returns:
        str: Formatted table as string
    """
    table = TableFormatter(border_style, truncation_mode, max_autosize_width)
    result = table.format_dict_table(data, columns, extractor, title)
    if print_output:
        print(result, end='')
    return result


def format_list_table(data: List[Union[Dict, List]],
                      columns: List[Tuple[str, int]],
                      extractor: Optional[Callable] = None,
                      title: str = None,
                      border_style: str = 'ascii',
                      truncation_mode: str = 'right',
                      max_autosize_width: int = 50,
                      print_output: bool = True) -> str:
    """
    Convenience function to quickly format a list as a table.

    Args:
        data (list): List of dictionaries or lists
        columns (list): List of tuples (column_name, width) where width=0 means autosize
        extractor (callable, optional): Function to extract row data
        title (str, optional): Table title
        border_style (str): Border style ('ascii', 'minimal')
        truncation_mode (str): Truncation mode ('right', 'left')
            - 'right': Ellipsis at beginning (default): "...end of text"
            - 'left': Ellipsis at end: "start of text..."
        max_autosize_width (int): Maximum width for autosize columns (default: 50)
        print_output (bool): Whether to print the table (default: True)

    Returns:
        str: Formatted table as string
    """
    table = TableFormatter(border_style, truncation_mode, max_autosize_width)
    result = table.format_list_table(data, columns, extractor, title)
    if print_output:
        print(result, end='')
    return result


def format_json_file(json_file_path: str,
                     columns: List[Tuple[str, int]],
                     extractor: Optional[Callable] = None,
                     title: str = None,
                     border_style: str = 'ascii',
                     truncation_mode: str = 'right',
                     max_autosize_width: int = 50,
                     print_output: bool = True) -> str:
    """
    Convenience function to quickly format JSON file data as a table.

    Args:
        json_file_path (str): Path to JSON file
        columns (list): List of tuples (column_name, width) where width=0 means autosize
        extractor (callable, optional): Function to extract row data
        title (str, optional): Table title
        border_style (str): Border style ('ascii', 'minimal')
        truncation_mode (str): Truncation mode ('right', 'left')
            - 'right': Ellipsis at beginning (default): "...end of text"
            - 'left': Ellipsis at end: "start of text..."
        max_autosize_width (int): Maximum width for autosize columns (default: 50)
        print_output (bool): Whether to print the table (default: True)

    Returns:
        str: Formatted table as string
    """
    table = TableFormatter(border_style, truncation_mode, max_autosize_width)
    result = table.format_json_file(json_file_path, columns, extractor, title)
    if print_output:
        print(result, end='')
    return result